// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using FCentricProspections.Server.DataModels;

namespace FCentricProspections.Server.Contexts;

public partial class FCentricSmallContext : DbContext
{
    public FCentricSmallContext(DbContextOptions<FCentricSmallContext> options)
        : base(options)
    {
    }

    // potentially more tables should be included

    public virtual DbSet<Address> Addresses { get; set; }

    public virtual DbSet<Brand> Brands { get; set; }

    public virtual DbSet<City> Cities { get; set; }

    public virtual DbSet<CompetitorBrand> CompetitorBrands { get; set; }

    public virtual DbSet<Contact> Contacts { get; set; }

    public virtual DbSet<Prospection> Prospections { get; set; }

    public virtual DbSet<ProspectionBrand> ProspectionBrands { get; set; }

    public virtual DbSet<ProspectionBrandInterest> ProspectionBrandInterests { get; set; }

    public virtual DbSet<ProspectionCompetitorBrand> ProspectionCompetitorBrands { get; set; }

    public virtual DbSet<ProspectionContactType> ProspectionContactTypes { get; set; }

    public virtual DbSet<ProspectionVisitType> ProspectionVisitTypes { get; set; }

    public virtual DbSet<Shop> Shops { get; set; }

    public virtual DbSet<User> Users { get; set; }


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Prospection>(entity =>
        {
            entity.HasKey(e => e.Id);
            entity.HasOne(d => d.Shop).WithMany(p => p.Prospections)
                .HasForeignKey(d => d.ShopId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_dbo.Prospections_dbo.Shops_ShopId");
        });

        // to implement ?

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}