// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using FCentricProspections.Server.Models;

namespace FCentricProspections.Server.Contexts;

public partial class FCentricSmallContext : DbContext
{
    public FCentricSmallContext(DbContextOptions<FCentricSmallContext> options)
        : base(options)
    {
    }

    // UNSURE: should all database tables be included?

    public virtual DbSet<Address> Addresses { get; set; }

    public virtual DbSet<City> Cities { get; set; }

    public virtual DbSet<Contact> Contacts { get; set; }

    // NEW
    public virtual DbSet<Prospection> Prospections { get; set; }

    public virtual DbSet<Shop> Shops { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // UNSURE: is it correct to only use modelBuilder for the new Prospection entity?
        // I had to manually adjust the Migration to make sure it only creates the Prospections table

        // NEW
        modelBuilder.Entity<Prospection>(entity =>
        {
            entity.HasKey(e => e.Id);
            entity.HasOne(d => d.Shop).WithMany(p => p.Prospections)
                .HasForeignKey(d => d.ShopId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_dbo.Prospections_dbo.Shops_ShopId");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}