// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class AccountingSession
{
    public long Id { get; set; }

    public DateTime Date { get; set; }

    public string FileName { get; set; }

    public string Remarks { get; set; }

    public bool IsAccepted { get; set; }

    public string AcceptComment { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long? AccountingSessionTypeId { get; set; }

    public bool IsExportedToAccounting { get; set; }

    public bool IsExportedToWps { get; set; }

    public virtual ICollection<AccountingSessionDocument> AccountingSessionDocuments { get; set; } = new List<AccountingSessionDocument>();

    public virtual AccountingSessionType AccountingSessionType { get; set; }

    public virtual ICollection<FdiExportSession> FdiExportSessions { get; set; } = new List<FdiExportSession>();

    public virtual User UserCreated { get; set; }
}