// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class AccountingSessionDocument
{
    public long Id { get; set; }

    public bool IsAccepted { get; set; }

    public string AccceptComment { get; set; }

    public long DocumentId { get; set; }

    public decimal? Discount { get; set; }

    public int JournalCode { get; set; }

    public string Period { get; set; }

    public string DocumentName { get; set; }

    public int Code { get; set; }

    public string CurrencyCode { get; set; }

    public decimal TotalEuro { get; set; }

    public decimal Total { get; set; }

    public decimal Base0 { get; set; }

    public decimal Base6 { get; set; }

    public decimal Base12 { get; set; }

    public decimal Base21 { get; set; }

    public decimal BaseIc { get; set; }

    public decimal BaseXp { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long? AccountingSessionId { get; set; }

    public decimal BaseContract { get; set; }

    public decimal Vat { get; set; }

    public int Bookings { get; set; }

    public int DocType { get; set; }

    public string TemplateNr { get; set; }

    public string CustomerName { get; set; }

    public string Currency { get; set; }

    public int Rate { get; set; }

    public int Decimals { get; set; }

    public int RateUnity { get; set; }

    public DateTime DocDate { get; set; }

    public DateTime DueDate { get; set; }

    public string Account { get; set; }

    public decimal DebCurr { get; set; }

    public decimal CredCurr { get; set; }

    public decimal? CredVat { get; set; }

    public decimal DebEuro { get; set; }

    public decimal CredEuro { get; set; }

    public decimal? CredVatEuro { get; set; }

    public decimal? DebVat { get; set; }

    public decimal? DebVatEuro { get; set; }

    public string FollowupBy { get; set; }

    public string CustomerDescription { get; set; }

    public bool Wps { get; set; }

    public virtual AccountingSession AccountingSession { get; set; }

    public virtual Document Document { get; set; }

    public virtual User UserCreated { get; set; }
}