// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FCentricProspections.Server.DataModels;

[NotMapped]
public partial class AccountingCode
{
    public long Id { get; set; }

    public string Code { get; set; }

    public int JournalCode { get; set; }

    public string InvoiceStartCode { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public int InvoiceNumberSubstringStart { get; set; }

    public int InvoiceNumberSubstringLength { get; set; }

    public int DocumentCodeLastSegmentLength { get; set; }

    public long? CompanyId { get; set; }

    public virtual ICollection<Agent> Agents { get; set; } = new List<Agent>();

    public virtual Company Company { get; set; }

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual ICollection<DocumentImportMeta> DocumentImportMeta { get; set; } = new List<DocumentImportMeta>();

    public virtual ICollection<FashionDocument> FashionDocuments { get; set; } = new List<FashionDocument>();

    public virtual ICollection<MiscDocumentLine> MiscDocumentLines { get; set; } = new List<MiscDocumentLine>();

    public virtual ICollection<Po> Pos { get; set; } = new List<Po>();

    public virtual ICollection<SalesCondition> SalesConditions { get; set; } = new List<SalesCondition>();

    [NotMapped]
    public virtual ICollection<SupplierVat> SupplierVatAccountingCodes { get; set; } = new List<SupplierVat>();

    public virtual ICollection<SupplierVat> SupplierVatBehaccountingCodes { get; set; } = new List<SupplierVat>();

    public virtual ICollection<SupplierVat> SupplierVatExcludedAccountingCodes { get; set; } = new List<SupplierVat>();

    public virtual ICollection<Supplier> Suppliers { get; set; } = new List<Supplier>();

    public virtual User UserCreated { get; set; }
}