// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class ActionList
{
    public long Id { get; set; }

    public int Order { get; set; }

    public long ActionId { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long? ReturnStateActionId { get; set; }

    public virtual Action Action { get; set; }

    public virtual ReturnStateAction ReturnStateAction { get; set; }

    public virtual User UserCreated { get; set; }
}