// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class AdvancedPayment
{
    public long Id { get; set; }

    public long SalesConditionId { get; set; }

    public long AppointmentId { get; set; }

    public long CustomerLegalHistoryId { get; set; }

    public DateTime OrderDate { get; set; }

    public decimal Amount { get; set; }

    public int Rate { get; set; }

    public DateTime? RappelDate { get; set; }

    public DateTime DueDate { get; set; }

    public decimal AmountPaid { get; set; }

    public DateTime? DatePaid { get; set; }

    public string Remarks { get; set; }

    public long AdvancedPaymentStateId { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual AdvancedPaymentState AdvancedPaymentState { get; set; }

    public virtual Appointment Appointment { get; set; }

    public virtual CustomerLegalHistory CustomerLegalHistory { get; set; }

    public virtual SalesCondition SalesCondition { get; set; }

    public virtual User UserCreated { get; set; }
}