// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class AgentRegion
{
    public long Id { get; set; }

    public long AgentId { get; set; }

    public long RegionId { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual Agent Agent { get; set; }

    public virtual Region Region { get; set; }

    public virtual User UserCreated { get; set; }
}