// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class Agent
{
    public long Id { get; set; }

    public long? ContactId { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long? AccountingCodeId { get; set; }

    public virtual AccountingCode AccountingCode { get; set; }

    public virtual ICollection<AgentContact> AgentContacts { get; set; } = new List<AgentContact>();

    public virtual ICollection<AgentProductLineDelivery> AgentProductLineDeliveries { get; set; } = new List<AgentProductLineDelivery>();

    public virtual ICollection<AgentRegion> AgentRegions { get; set; } = new List<AgentRegion>();

    public virtual Contact Contact { get; set; }

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual ICollection<Document> Documents { get; set; } = new List<Document>();

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    public virtual ICollection<SalesCondition> SalesConditions { get; set; } = new List<SalesCondition>();

    public virtual User UserCreated { get; set; }
}