// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class AppointmentDepartmentResponsible
{
    public long Id { get; set; }

    public long SalesPeriodId { get; set; }

    public long CustomerId { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long DepartmentId { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Department Department { get; set; }

    public virtual SalesPeriod SalesPeriod { get; set; }

    public virtual User UserCreated { get; set; }
}