// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class AppointmentCaresponsible
{
    public long Id { get; set; }

    public long SalesPeriodId { get; set; }

    public long EmployeeId { get; set; }

    public string From { get; set; }

    public string To { get; set; }

    public int TotalAppoitments { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual SalesPeriod SalesPeriod { get; set; }

    public virtual User UserCreated { get; set; }
}