// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class Appointment
{
    public long Id { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public long EmployeeId { get; set; }

    public string Remarks { get; set; }

    public long AppointmentStateId { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsFixedAppointment { get; set; }

    public string RecurringKey { get; set; }

    public virtual ICollection<AdvancedPayment> AdvancedPayments { get; set; } = new List<AdvancedPayment>();

    public virtual ICollection<AppointmentContact> AppointmentContacts { get; set; } = new List<AppointmentContact>();

    public virtual AppointmentState AppointmentState { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual RoadAppointment RoadAppointment { get; set; }

    public virtual ShowroomAppointment ShowroomAppointment { get; set; }

    public virtual User UserCreated { get; set; }
}