// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class AppVersion
{
    public long Id { get; set; }

    public string LastVersionNumberAndroid { get; set; }

    public string MandatoryVersionNumberAndroid { get; set; }

    public string LastVersionNumberiOs { get; set; }

    public string MandatoryVersionNumberiOs { get; set; }
}