// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class AvailabilityDay
{
    public long Id { get; set; }

    public int Order { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual ICollection<ShopAvailability> ShopAvailabilities { get; set; } = new List<ShopAvailability>();

    public virtual User UserCreated { get; set; }
}