// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class Barcode
{
    public long Id { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long? BarcodeId { get; set; }

    public virtual Barcode BarcodeNavigation { get; set; }

    public virtual ICollection<BiEmployeeDailyBarcodeResult> BiEmployeeDailyBarcodeResults { get; set; } = new List<BiEmployeeDailyBarcodeResult>();

    public virtual ICollection<DocumentLineDetail> DocumentLineDetails { get; set; } = new List<DocumentLineDetail>();

    public virtual ICollection<Document> Documents { get; set; } = new List<Document>();

    public virtual FashionBarcode FashionBarcode { get; set; }

    public virtual ICollection<Barcode> InverseBarcodeNavigation { get; set; } = new List<Barcode>();

    public virtual ICollection<Invitation> Invitations { get; set; } = new List<Invitation>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual User UserCreated { get; set; }

    public virtual VoucherBarcode VoucherBarcode { get; set; }
}