// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class BiEmployeeDailyGroupResult
{
    public long Id { get; set; }

    public DateTime Date { get; set; }

    public long EmployeeId { get; set; }

    public string Group { get; set; }

    public int Tickets { get; set; }

    public int Pieces { get; set; }

    public decimal SalesResult { get; set; }

    public decimal Discount { get; set; }

    public decimal PurchaseValue { get; set; }

    public long PosId { get; set; }

    public decimal LoyaltyDiscount { get; set; }

    public virtual Employee Employee { get; set; }
}