// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class BiShopDailySeasonalBrandResult
{
    public long Id { get; set; }

    public DateTime Date { get; set; }

    public long StockLocationId { get; set; }

    public long BrandId { get; set; }

    public long SalesPeriodId { get; set; }

    public decimal SalesResult { get; set; }

    public decimal SalesResultPy { get; set; }

    public virtual Brand Brand { get; set; }

    public virtual SalesPeriod SalesPeriod { get; set; }

    public virtual StockLocation StockLocation { get; set; }
}