// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class BleckmannTransportState
{
    public long Id { get; set; }

    public string Code { get; set; }

    public bool MailCa { get; set; }

    public bool MailFinance { get; set; }

    public bool MailReturnResponsible { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual ICollection<DocumentBleckmannTransportState> DocumentBleckmannTransportStates { get; set; } = new List<DocumentBleckmannTransportState>();

    public virtual User UserCreated { get; set; }
}