// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class BlockedByFdiReason
{
    public long Id { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public bool IsCancel { get; set; }

    public string WpsCode { get; set; }

    public virtual ICollection<CustomerWpsStatus> CustomerWpsStatuses { get; set; } = new List<CustomerWpsStatus>();

    public virtual ICollection<Document> Documents { get; set; } = new List<Document>();

    public virtual User UserCreated { get; set; }
}