// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class City
{
    public long Id { get; set; }

    public string PostalCode { get; set; }

    public long CountryId { get; set; }

    public long? ProvinceId { get; set; }

    public long? RegionId { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public string SearchName { get; set; }

    public virtual ICollection<Address> Addresses { get; set; } = new List<Address>();

    public virtual ICollection<CityPriceRegion> CityPriceRegions { get; set; } = new List<CityPriceRegion>();

    public virtual Country Country { get; set; }

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual Province Province { get; set; }

    public virtual Region Region { get; set; }

    public virtual ICollection<Supplier> Suppliers { get; set; } = new List<Supplier>();

    public virtual User UserCreated { get; set; }
}