// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class CollectionSaleSignUp
{
    public long Id { get; set; }

    public long InvitationTypeId { get; set; }

    public long CustomerInvitationId { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual CustomerInvitation CustomerInvitation { get; set; }

    public virtual InvitationType InvitationType { get; set; }

    public virtual User UserCreated { get; set; }
}