// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class CollectionSalesInvitation
{
    public long Id { get; set; }

    public long CollectionSalesInvitationTypeId { get; set; }

    public int NumberOfPeople { get; set; }

    public bool ReceivedInvitation { get; set; }

    public bool IsActive { get; set; }

    public bool Unsubscribed { get; set; }

    public bool ReceivedInitialMail { get; set; }

    public string MailErrors { get; set; }

    public long? DateId { get; set; }

    public DateTime? DateUpdated { get; set; }

    public virtual CollectionSalesInvitationType CollectionSalesInvitationType { get; set; }

    public virtual Invitation IdNavigation { get; set; }
}