// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class Color
{
    public long Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long SupplierId { get; set; }

    public virtual ICollection<FashionBarcode> FashionBarcodes { get; set; } = new List<FashionBarcode>();

    public virtual ICollection<FashionProductColor> FashionProductColors { get; set; } = new List<FashionProductColor>();

    public virtual ICollection<FashionProductPicture> FashionProductPictures { get; set; } = new List<FashionProductPicture>();

    public virtual Supplier Supplier { get; set; }

    public virtual User UserCreated { get; set; }
}