// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class ConfigurationSetting
{
    public long Id { get; set; }

    public int Key { get; set; }

    public string Value { get; set; }
}