// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class ContactChannel
{
    public long Id { get; set; }

    public string Value { get; set; }

    public string Remarks { get; set; }

    public long ContactChannelDescriptionId { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long? ContactId { get; set; }

    public bool UseForAppointmentEmails { get; set; }

    public virtual Contact Contact { get; set; }

    public virtual ContactChannelDescription ContactChannelDescription { get; set; }

    public virtual ICollection<ContactChannelInterest> ContactChannelInterests { get; set; } = new List<ContactChannelInterest>();

    public virtual ICollection<ContactChannelOptIn> ContactChannelOptIns { get; set; } = new List<ContactChannelOptIn>();

    public virtual User UserCreated { get; set; }
}