// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FCentricProspections.Server.DataModels;

public partial class ContractState
{
    public long Id { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    [NotMapped]
    public virtual ICollection<ShowroomAppointmentSalesCondition> ShowroomAppointmentSalesConditionContractStates { get; set; } = new List<ShowroomAppointmentSalesCondition>();

    [NotMapped]
    public virtual ICollection<ShowroomAppointmentSalesCondition> ShowroomAppointmentSalesConditionUpfrontPaymentContractStates { get; set; } = new List<ShowroomAppointmentSalesCondition>();

    public virtual User UserCreated { get; set; }
}