// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class ContactChannelInterest
{
    public long Id { get; set; }

    public long ContactChannelId { get; set; }

    public long ContactChannelInterestTypeId { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual ContactChannel ContactChannel { get; set; }

    public virtual ContactChannelInterestType ContactChannelInterestType { get; set; }

    public virtual User UserCreated { get; set; }
}