// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FCentricProspections.Server.DataModels;

public partial class Contact
{
    public long Id { get; set; }

    public long? LanguageId { get; set; }

    public string FirstName { get; set; }

    public bool IsSupplierContact { get; set; }

    public long? AddressId { get; set; }

    public string Remarks { get; set; }

    public bool IsHidden { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long? WebUserId { get; set; }

    public string SearchName { get; set; }

    public string SearchName2 { get; set; }

    public virtual Address Address { get; set; }

    public virtual ICollection<AgentContact> AgentContacts { get; set; } = new List<AgentContact>();

    public virtual ICollection<Agent> Agents { get; set; } = new List<Agent>();

    public virtual ICollection<AppointmentContact> AppointmentContacts { get; set; } = new List<AppointmentContact>();

    public virtual ICollection<ContactChannel> ContactChannels { get; set; } = new List<ContactChannel>();

    public virtual ICollection<CustomerContact> CustomerContacts { get; set; } = new List<CustomerContact>();

    public virtual ICollection<CustomerLegalHistory> CustomerLegalHistories { get; set; } = new List<CustomerLegalHistory>();

    [NotMapped]
    public virtual ICollection<Document> DocumentContacts { get; set; } = new List<Document>();

    [NotMapped]
    public virtual ICollection<Document> DocumentWebUserCreateds { get; set; } = new List<Document>();

    public virtual ICollection<FashionDocument> FashionDocuments { get; set; } = new List<FashionDocument>();

    public virtual Language Language { get; set; }

    public virtual ICollection<ShopContact> ShopContacts { get; set; } = new List<ShopContact>();

    public virtual ICollection<Shop> Shops { get; set; } = new List<Shop>();

    public virtual ICollection<Showroom> Showrooms { get; set; } = new List<Showroom>();

    public virtual ICollection<StockLocation> StockLocations { get; set; } = new List<StockLocation>();

    public virtual ICollection<SupplierContact> SupplierContacts { get; set; } = new List<SupplierContact>();

    public virtual User UserCreated { get; set; }

    public virtual WebUser WebUser { get; set; }
}