// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class Contact
{
    public long Id { get; set; }

    public long? LanguageId { get; set; }

    public string FirstName { get; set; }

    public bool IsSupplierContact { get; set; }

    public long? AddressId { get; set; }

    public string Remarks { get; set; }

    public bool IsHidden { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long? WebUserId { get; set; }

    public string SearchName { get; set; }

    public string SearchName2 { get; set; }

    public virtual Address Address { get; set; }

    public virtual ICollection<CustomerLegalHistory> CustomerLegalHistories { get; set; } = new List<CustomerLegalHistory>();

    public virtual Language Language { get; set; }

    public virtual ICollection<ShopContact> ShopContacts { get; set; } = new List<ShopContact>();

    public virtual ICollection<Shop> Shops { get; set; } = new List<Shop>();

    public virtual User UserCreated { get; set; }
}