// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class Country
{
    public long Id { get; set; }

    public string Code { get; set; }

    public long CurrencyId { get; set; }

    public long PaymentConditionId { get; set; }

    public long? VatTypeId { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual ICollection<City> Cities { get; set; } = new List<City>();

    public virtual Currency Currency { get; set; }

    public virtual PaymentCondition PaymentCondition { get; set; }

    public virtual ICollection<Province> Provinces { get; set; } = new List<Province>();

    public virtual ICollection<PublicHoliday> PublicHolidays { get; set; } = new List<PublicHoliday>();

    public virtual ICollection<PublicationCountry> PublicationCountries { get; set; } = new List<PublicationCountry>();

    public virtual ICollection<ShopDelivery> ShopDeliveries { get; set; } = new List<ShopDelivery>();

    public virtual ICollection<SupplierVat> SupplierVats { get; set; } = new List<SupplierVat>();

    public virtual User UserCreated { get; set; }

    public virtual VatType VatType { get; set; }
}