// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class CustomerLegalHistory
{
    public long Id { get; set; }

    public long? CustomerCodeId { get; set; }

    public long CustomerId { get; set; }

    public string VatNr { get; set; }

    public int VatCheckState { get; set; }

    public string VatCheckDate { get; set; }

    public string Kvk { get; set; }

    public long LegalContactId { get; set; }

    public string RequestIdentifier { get; set; }

    public long? LegalFormId { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public string VatNrSearch { get; set; }

    public virtual ICollection<AdvancedPayment> AdvancedPayments { get; set; } = new List<AdvancedPayment>();

    public virtual Customer Customer { get; set; }

    public virtual CustomerCode CustomerCode { get; set; }

    public virtual ICollection<FashionDocument> FashionDocuments { get; set; } = new List<FashionDocument>();

    public virtual Contact LegalContact { get; set; }

    public virtual LegalForm LegalForm { get; set; }

    public virtual User UserCreated { get; set; }
}