// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class CustomerType
{
    public long Id { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public bool ExludeVat { get; set; }

    public bool HasToOptIn { get; set; }

    public virtual ICollection<CustomerTypeFeature> CustomerTypeFeatures { get; set; } = new List<CustomerTypeFeature>();

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual User UserCreated { get; set; }
}