// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class Customer
{
    public long Id { get; set; }

    public string City { get; set; }

    public string Country { get; set; }

    public decimal Discount { get; set; }

    public long? DeliveryMethodId { get; set; }

    public long? UpfrontPaymentId { get; set; }

    public long? PaymentConditionId { get; set; }

    public long? CurrencyId { get; set; }

    public long? BlockedTypeId { get; set; }

    public DateTime? BlockedDate { get; set; }

    public string BlockedReason { get; set; }

    public string Remarks { get; set; }

    public string AccountNr { get; set; }

    public string Iban { get; set; }

    public string Bic { get; set; }

    public string BankName { get; set; }

    public long? BankCityId { get; set; }

    public long? VatTypeId { get; set; }

    public long? KeyAccountManagerId { get; set; }

    public long DeliveryLocationTypeId { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public bool IsKeyAccount { get; set; }

    public string SearchName { get; set; }

    public bool IsPosCustomer { get; set; }

    public bool Top50 { get; set; }

    public bool Dd { get; set; }

    public long? CustomerTypeId { get; set; }

    public int AttendedCollectionSale { get; set; }

    public bool IsPrivate { get; set; }

    public string CollectionSaleCustomerCode { get; set; }

    public decimal? MaximumBudget { get; set; }

    public bool IgnoreAutomaticOverrule { get; set; }

    public bool IsDeleted { get; set; }

    public long? AgentId { get; set; }

    public bool CanAlwaysSwap { get; set; }

    public string GlobalLocationNumber { get; set; }

    public bool AgreeToUseTheirData { get; set; }

    public long? CustomerLoyaltyId { get; set; }

    public DateTime? AnniversaryDay { get; set; }

    public long? AccountingCodeId { get; set; }

    public bool IsKeyClient { get; set; }

    public long? GenderId { get; set; }

    public string MiscAccountingCode { get; set; }

    public DateTime? DateUpdated { get; set; }

    public bool IgnoreInReporting { get; set; }

    public virtual AccountingCode AccountingCode { get; set; }

    public virtual Agent Agent { get; set; }

    public virtual ICollection<AppointmentDepartmentResponsible> AppointmentDepartmentResponsibles { get; set; } = new List<AppointmentDepartmentResponsible>();

    public virtual City BankCity { get; set; }

    public virtual BlockedType BlockedType { get; set; }

    public virtual Currency Currency { get; set; }

    public virtual ICollection<CustomerContact> CustomerContacts { get; set; } = new List<CustomerContact>();

    public virtual ICollection<CustomerGuarantee> CustomerGuarantees { get; set; } = new List<CustomerGuarantee>();

    public virtual ICollection<CustomerInvitation> CustomerInvitations { get; set; } = new List<CustomerInvitation>();

    public virtual ICollection<CustomerLegalHistory> CustomerLegalHistories { get; set; } = new List<CustomerLegalHistory>();

    public virtual CustomerLoyalty CustomerLoyalty { get; set; }

    public virtual ICollection<CustomerRule> CustomerRules { get; set; } = new List<CustomerRule>();

    public virtual ICollection<CustomerShop> CustomerShops { get; set; } = new List<CustomerShop>();

    public virtual CustomerType CustomerType { get; set; }

    public virtual ICollection<CustomerWifiCode> CustomerWifiCodes { get; set; } = new List<CustomerWifiCode>();

    public virtual ICollection<CustomerWpsStatus> CustomerWpsStatuses { get; set; } = new List<CustomerWpsStatus>();

    public virtual DeliveryLocationType DeliveryLocationType { get; set; }

    public virtual DeliveryMethod DeliveryMethod { get; set; }

    public virtual ICollection<EdiMessage> EdiMessages { get; set; } = new List<EdiMessage>();

    public virtual ICollection<EnemyRule> EnemyRules { get; set; } = new List<EnemyRule>();

    public virtual Gender Gender { get; set; }

    public virtual Employee KeyAccountManager { get; set; }

    public virtual ICollection<KlaviyoCollectionSaleCustomerSync> KlaviyoCollectionSaleCustomerSyncs { get; set; } = new List<KlaviyoCollectionSaleCustomerSync>();

    public virtual PaymentCondition PaymentCondition { get; set; }

    public virtual UpfrontPayment UpfrontPayment { get; set; }

    public virtual User UserCreated { get; set; }

    public virtual VatType VatType { get; set; }
}