// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class CustomerTypeFeature
{
    public long Id { get; set; }

    public long FeatureId { get; set; }

    public long CustomerTypeId { get; set; }

    public bool CanAdd { get; set; }

    public bool CanSearch { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual CustomerType CustomerType { get; set; }

    public virtual Feature Feature { get; set; }

    public virtual User UserCreated { get; set; }
}