// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class CustomerLoyalty
{
    public long Id { get; set; }

    public DateTime ExpirationDate { get; set; }

    public DateTime StartDate { get; set; }

    public long LoyaltyTypeId { get; set; }

    public long CustomerId { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public decimal CurrentAmount { get; set; }

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual ICollection<DocumentPayment> DocumentPayments { get; set; } = new List<DocumentPayment>();

    public virtual LoyaltyType LoyaltyType { get; set; }

    public virtual User UserCreated { get; set; }
}