// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class CustomerInvitation
{
    public long Id { get; set; }

    public long CustomerId { get; set; }

    public long InvitationId { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual ICollection<CollectionSaleSignUp> CollectionSaleSignUps { get; set; } = new List<CollectionSaleSignUp>();

    public virtual Customer Customer { get; set; }

    public virtual Invitation Invitation { get; set; }

    public virtual User UserCreated { get; set; }
}