// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class CustomerOptIn
{
    public long Id { get; set; }

    public bool IsOptIn { get; set; }

    public string EmailAddress { get; set; }

    public string LanguageCode { get; set; }

    public Guid Guid { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual User UserCreated { get; set; }
}