// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class CustomerWpsStatus
{
    public long Id { get; set; }

    public long CustomerId { get; set; }

    public long? BlockedByFdiReasonId { get; set; }

    public bool IsBlocked { get; set; }

    public bool IsPrepayment { get; set; }

    public string Response { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual BlockedByFdiReason BlockedByFdiReason { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual User UserCreated { get; set; }
}