// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class CustomerBlockedRule
{
    public long Id { get; set; }

    public long BlockedTypeId { get; set; }

    public DateTime Date { get; set; }

    public virtual BlockedType BlockedType { get; set; }

    public virtual Rule IdNavigation { get; set; }
}