// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class CustomerWifiCode
{
    public long Id { get; set; }

    public long CustomerId { get; set; }

    public long WifiCodeId { get; set; }

    public DateTime DateAssigned { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual User UserCreated { get; set; }

    public virtual WifiCode WifiCode { get; set; }
}