// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class DedicatedSalesRule
{
    public long Id { get; set; }

    public long EmployeeId { get; set; }

    public long? ProductLineId { get; set; }

    public long? SalesPeriodId { get; set; }

    public long? SupplierId { get; set; }

    public long? ProductLineDeliveryId { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual Rule IdNavigation { get; set; }

    public virtual ProductLine ProductLine { get; set; }

    public virtual ProductLineDelivery ProductLineDelivery { get; set; }

    public virtual SalesPeriod SalesPeriod { get; set; }

    public virtual Supplier Supplier { get; set; }
}