// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class DelayedDeliveryRule
{
    public long Id { get; set; }

    public long SalesPeriodId { get; set; }

    public long? ProductLineDeliveryId { get; set; }

    public DateTime Date { get; set; }

    public virtual ICollection<DelayedDeliveryRuleProductLineDelivery> DelayedDeliveryRuleProductLineDeliveries { get; set; } = new List<DelayedDeliveryRuleProductLineDelivery>();

    public virtual ICollection<DelayedDeliveryRuleShop> DelayedDeliveryRuleShops { get; set; } = new List<DelayedDeliveryRuleShop>();

    public virtual ICollection<DelayedDeliveryRuleSupplier> DelayedDeliveryRuleSuppliers { get; set; } = new List<DelayedDeliveryRuleSupplier>();

    public virtual Rule IdNavigation { get; set; }

    public virtual ProductLineDelivery ProductLineDelivery { get; set; }

    public virtual SalesPeriod SalesPeriod { get; set; }
}