// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class DelayedDeliveryProposedRule
{
    public long Id { get; set; }

    public long SalesPeriodId { get; set; }

    public long? ProductLineDeliveryId { get; set; }

    public DateTime Date { get; set; }

    public virtual ICollection<DelayedDeliveryProposedRuleShop> DelayedDeliveryProposedRuleShops { get; set; } = new List<DelayedDeliveryProposedRuleShop>();

    public virtual ProposedRule IdNavigation { get; set; }

    public virtual ProductLineDelivery ProductLineDelivery { get; set; }

    public virtual SalesPeriod SalesPeriod { get; set; }
}