// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class DeliveryWindow
{
    public long Id { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual ICollection<DocumentLine> DocumentLines { get; set; } = new List<DocumentLine>();

    public virtual ICollection<ProductDeliveryWindow> ProductDeliveryWindows { get; set; } = new List<ProductDeliveryWindow>();

    public virtual User UserCreated { get; set; }
}