// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class DiscountCampaignLine
{
    public long Id { get; set; }

    public long DiscountCampaignId { get; set; }

    public long? ShopId { get; set; }

    public long? SalesPeriodId { get; set; }

    public long? BrandId { get; set; }

    public long? ProductLineDeliveryId { get; set; }

    public long? ProductGroupId { get; set; }

    public int? DiscountOverride { get; set; }

    public bool IsActive { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public int MinQuantity { get; set; }

    public int? MaxQuantity { get; set; }

    public bool ShowOnTicket { get; set; }

    public virtual Brand Brand { get; set; }

    public virtual DiscountCampaign DiscountCampaign { get; set; }

    public virtual ICollection<DiscountCampaignLineDetail> DiscountCampaignLineDetails { get; set; } = new List<DiscountCampaignLineDetail>();

    public virtual ICollection<PosDocumentLine> PosDocumentLines { get; set; } = new List<PosDocumentLine>();

    public virtual ProductGroup ProductGroup { get; set; }

    public virtual ProductLineDelivery ProductLineDelivery { get; set; }

    public virtual SalesPeriod SalesPeriod { get; set; }

    public virtual Shop Shop { get; set; }

    public virtual User UserCreated { get; set; }
}