// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class DiscountCampaignLineDetail
{
    public long Id { get; set; }

    public long DiscountCampaignLineId { get; set; }

    public bool IsActive { get; set; }

    public long ProductId { get; set; }

    public bool IsIncluded { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual DiscountCampaignLine DiscountCampaignLine { get; set; }

    public virtual FashionProduct Product { get; set; }

    public virtual User UserCreated { get; set; }
}