// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class DiscountRuleRule
{
    public long Id { get; set; }

    public long SalesPeriodId { get; set; }

    public long? ProductLineDeliveryId { get; set; }

    public int Discount { get; set; }

    public virtual ICollection<DiscountRuleSupplier> DiscountRuleSuppliers { get; set; } = new List<DiscountRuleSupplier>();

    public virtual Rule IdNavigation { get; set; }

    public virtual ProductLineDelivery ProductLineDelivery { get; set; }

    public virtual SalesPeriod SalesPeriod { get; set; }
}