// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class DocumentImportConfigurationMapping
{
    public long Id { get; set; }

    public string Source { get; set; }

    public int Target { get; set; }

    public long? DocumentImportConfigurationId { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public string Modifiers { get; set; }

    public string ModifierParams { get; set; }

    public string FixedCellCoordinate { get; set; }

    public virtual DocumentImportConfiguration DocumentImportConfiguration { get; set; }

    public virtual User UserCreated { get; set; }
}