// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class DocumentImportConfiguration
{
    public long Id { get; set; }

    public long SupplierId { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long? DocumentTypeId { get; set; }

    public int? DataRow { get; set; }

    public int NrOfFooterRows { get; set; }

    public virtual ICollection<DocumentImportConfigurationMapping> DocumentImportConfigurationMappings { get; set; } = new List<DocumentImportConfigurationMapping>();

    public virtual ICollection<DocumentImportMeta> DocumentImportMeta { get; set; } = new List<DocumentImportMeta>();

    public virtual DocumentType DocumentType { get; set; }

    public virtual Supplier Supplier { get; set; }

    public virtual User UserCreated { get; set; }
}