// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class DocumentImportMetaError
{
    public long Id { get; set; }

    public long DocumentImportMetaId { get; set; }

    public string Error { get; set; }

    public string SupplierCode { get; set; }

    public string ShopName { get; set; }

    public long? ProductId { get; set; }

    public string Color { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public string Size { get; set; }

    public string Barcode { get; set; }

    public long SupplierId { get; set; }

    public string ColorName { get; set; }

    public virtual DocumentImportMeta DocumentImportMeta { get; set; }

    public virtual User UserCreated { get; set; }
}