// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class DocumentLine
{
    public long Id { get; set; }

    public string Remarks { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long DocumentId { get; set; }

    public long? DocumentLineReferenceId { get; set; }

    public string BoxNr { get; set; }

    public decimal DiscountPercentage { get; set; }

    public long? DeliveryWindowId { get; set; }

    public long? StockLocationId { get; set; }

    public decimal DiscountAmount { get; set; }

    public long? SizePackId { get; set; }

    public int? SizePackQuantity { get; set; }

    public long? BatchId { get; set; }

    public virtual DeliveryWindow DeliveryWindow { get; set; }

    public virtual Document Document { get; set; }

    public virtual ICollection<DocumentLineDetail> DocumentLineDetails { get; set; } = new List<DocumentLineDetail>();

    public virtual DocumentLine DocumentLineReference { get; set; }

    public virtual ICollection<DocumentLine> InverseDocumentLineReference { get; set; } = new List<DocumentLine>();

    public virtual MiscDocumentLine MiscDocumentLine { get; set; }

    public virtual PosDocumentLine PosDocumentLine { get; set; }

    public virtual SizePack SizePack { get; set; }

    public virtual StockLocation StockLocation { get; set; }

    public virtual User UserCreated { get; set; }
}