// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class DocumentImportMetaDetail
{
    public long Id { get; set; }

    public long DocumentImportMetaId { get; set; }

    public long ProductId { get; set; }

    public long ProductSizeId { get; set; }

    public long ProductColorId { get; set; }

    public long ShopId { get; set; }

    public long? StockLocationId { get; set; }

    public string BoxNumber { get; set; }

    public string Quantity { get; set; }

    public virtual DocumentImportMeta DocumentImportMeta { get; set; }

    public virtual StockLocation StockLocation { get; set; }
}