// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class DocumentBleckmannTransportState
{
    public long Id { get; set; }

    public long BleckmannTransportStateId { get; set; }

    public DateTime DateTime { get; set; }

    public string Remarks { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long? DocumentId { get; set; }

    public virtual BleckmannTransportState BleckmannTransportState { get; set; }

    public virtual Document Document { get; set; }

    public virtual User UserCreated { get; set; }
}