// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FCentricProspections.Server.DataModels;

public partial class Document
{
    public long Id { get; set; }

    public long DocumentTypeId { get; set; }

    public long DocumentStateId { get; set; }

    public long? EmployeeId { get; set; }

    public long ContactId { get; set; }

    public decimal? Discount { get; set; }

    public DateTime? DueDate { get; set; }

    public int Pieces { get; set; }

    public decimal Amount { get; set; }

    public decimal DiscountAmount { get; set; }

    public decimal VatAmount { get; set; }

    public decimal Total { get; set; }

    public string Remarks { get; set; }

    public long BarcodeId { get; set; }

    public DateTime Date { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public decimal TransportCost { get; set; }

    public long DocumentDeliveryStateId { get; set; }

    public string DocumentDeliverStateRemarks { get; set; }

    public DateTime? DeliveryDate { get; set; }

    public string ExternalRemarks { get; set; }

    public long? BlockedByFdiReasonId { get; set; }

    public Guid Key { get; set; }

    public bool IgnoreFlowControl { get; set; }

    public string FlowControlRemarks { get; set; }

    public long? WebUserCreatedId { get; set; }

    public long? WpsPrePaymentId { get; set; }

    public long? VatTypeId { get; set; }

    public int PosMode { get; set; }

    public string DiscountRemarks { get; set; }

    public long? AgentId { get; set; }

    public long? TransportTypeId { get; set; }

    public bool IsCommission { get; set; }

    public bool IsWpsCustomer { get; set; }

    public decimal? Addition { get; set; }

    public string StorageUrl { get; set; }

    public bool HasUpToDateVersionInCloud { get; set; }

    public decimal VoucherTotal { get; set; }

    public decimal PaymentTotal { get; set; }

    public bool ReorderOnly { get; set; }

    public virtual ICollection<AccountingSessionDocument> AccountingSessionDocuments { get; set; } = new List<AccountingSessionDocument>();

    public virtual Agent Agent { get; set; }

    public virtual Barcode Barcode { get; set; }

    public virtual BlockedByFdiReason BlockedByFdiReason { get; set; }

    public virtual Contact Contact { get; set; }

    public virtual ICollection<DocumentBleckmannTransportState> DocumentBleckmannTransportStates { get; set; } = new List<DocumentBleckmannTransportState>();

    public virtual DocumentDeliveryState DocumentDeliveryState { get; set; }

    public virtual ICollection<DocumentLine> DocumentLines { get; set; } = new List<DocumentLine>();

    public virtual ICollection<DocumentPayment> DocumentPayments { get; set; } = new List<DocumentPayment>();
    
    [NotMapped]
    public virtual ICollection<DocumentRelation> DocumentRelationSourceDocuments { get; set; } = new List<DocumentRelation>();

    [NotMapped]
    public virtual ICollection<DocumentRelation> DocumentRelationTargetDocuments { get; set; } = new List<DocumentRelation>();

    public virtual ICollection<DocumentRule> DocumentRules { get; set; } = new List<DocumentRule>();

    [NotMapped]
    public virtual ICollection<DocumentSnapshot> DocumentSnapshotDocuments { get; set; } = new List<DocumentSnapshot>();

    [NotMapped]
    public virtual ICollection<DocumentSnapshot> DocumentSnapshotSnapshotDocuments { get; set; } = new List<DocumentSnapshot>();

    public virtual DocumentState DocumentState { get; set; }

    public virtual DocumentType DocumentType { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual FashionDocument FashionDocument { get; set; }

    public virtual ICollection<FdiExportSessionDocument> FdiExportSessionDocuments { get; set; } = new List<FdiExportSessionDocument>();

    public virtual ICollection<KlaviyoDocumentSync> KlaviyoDocumentSyncs { get; set; } = new List<KlaviyoDocumentSync>();

    public virtual ICollection<KlaviyoRetailDocumentSync> KlaviyoRetailDocumentSyncs { get; set; } = new List<KlaviyoRetailDocumentSync>();

    public virtual TransportType TransportType { get; set; }

    public virtual User UserCreated { get; set; }

    public virtual VatType VatType { get; set; }

    public virtual Contact WebUserCreated { get; set; }

    public virtual WpsPrePayment WpsPrePayment { get; set; }
}