// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class DocumentImportMeta
{
    public long Id { get; set; }

    public string FileName { get; set; }

    public long SalesPeriodId { get; set; }

    public long DocumentTypeId { get; set; }

    public long? SupplierId { get; set; }

    public byte[] File { get; set; }

    public long? PosId { get; set; }

    public int TotalQuantity { get; set; }

    public long? DocumentImportConfigurationId { get; set; }

    public long? FileImportLogTypeId { get; set; }

    public DateTime? DocumentDate { get; set; }

    public string SupplierReference { get; set; }

    public int SheetIndex { get; set; }

    public long DocumentImportMetaStatusId { get; set; }

    public long? AccountingCodeId { get; set; }

    public bool IsFcx { get; set; }

    public bool HasErrorsOnPrepare { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public int FirstDataRow { get; set; }

    public bool IsLjjv { get; set; }

    public string ShopSupplierCode { get; set; }

    public string ShopName { get; set; }

    public string InvoiceReference { get; set; }

    public string ImportRemark { get; set; }

    public virtual AccountingCode AccountingCode { get; set; }

    public virtual DocumentImportConfiguration DocumentImportConfiguration { get; set; }

    public virtual ICollection<DocumentImportMetaDetail> DocumentImportMetaDetails { get; set; } = new List<DocumentImportMetaDetail>();

    public virtual ICollection<DocumentImportMetaError> DocumentImportMetaErrors { get; set; } = new List<DocumentImportMetaError>();

    public virtual DocumentImportMetaStatus DocumentImportMetaStatus { get; set; }

    public virtual ICollection<DocumentImportMetaWarning> DocumentImportMetaWarnings { get; set; } = new List<DocumentImportMetaWarning>();

    public virtual DocumentType DocumentType { get; set; }

    public virtual Po Pos { get; set; }

    public virtual SalesPeriod SalesPeriod { get; set; }

    public virtual Supplier Supplier { get; set; }

    public virtual User UserCreated { get; set; }
}