// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class DocumentPayment
{
    public long Id { get; set; }

    public decimal Amount { get; set; }

    public long? VoucherId { get; set; }

    public string CreditCardNumber { get; set; }

    public string Remarks { get; set; }

    public long DocumentPaymentTypeId { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long DocumentId { get; set; }

    public bool IsLocked { get; set; }

    public string OpiPrintRequest { get; set; }

    public string OpiMerchantPrintRequest { get; set; }

    public long? PosEjournalId { get; set; }

    public string ItsrequestId { get; set; }

    public DateTime Date { get; set; }

    public long? CustomerLoyaltyId { get; set; }

    public virtual CustomerLoyalty CustomerLoyalty { get; set; }

    public virtual Document Document { get; set; }

    public virtual DocumentPaymentType DocumentPaymentType { get; set; }

    public virtual PosEjournal PosEjournal { get; set; }

    public virtual User UserCreated { get; set; }

    public virtual Voucher Voucher { get; set; }
}