// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class DocumentLineDetail
{
    public long Id { get; set; }

    public long DocumentLineId { get; set; }

    public long BarcodeId { get; set; }

    public int Quantity { get; set; }

    public int TransferQuantity { get; set; }

    public int RestQuantity { get; set; }

    public decimal PurchasePrice { get; set; }

    public decimal SalesPrice { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long VatId { get; set; }

    public long? BarcodeAliasId { get; set; }

    public decimal? OriginalSalesPrice { get; set; }

    public long? FifoPurchasePriceDldRef { get; set; }

    public virtual Barcode Barcode { get; set; }

    public virtual DocumentLine DocumentLine { get; set; }

    public virtual User UserCreated { get; set; }

    public virtual Vat Vat { get; set; }
}