// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class DocumentImportMetaWarning
{
    public long Id { get; set; }

    public long DocumentImportMetaId { get; set; }

    public string Description { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual DocumentImportMeta DocumentImportMeta { get; set; }

    public virtual User UserCreated { get; set; }
}