// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class DocumentRelation
{
    public long Id { get; set; }

    public long SourceDocumentId { get; set; }

    public long TargetDocumentId { get; set; }

    public string Remarks { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual Document SourceDocument { get; set; }

    public virtual Document TargetDocument { get; set; }

    public virtual User UserCreated { get; set; }
}