// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class EliBudget
{
    public string Product { get; set; }

    public string ShopCode { get; set; }
}