// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class EliOrderDate
{
    public string ShopCode { get; set; }

    public string OrderNr { get; set; }

    public string OrderDate { get; set; }

    public string ProductCode { get; set; }
}