// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class EmployeeSeasonalCost
{
    public long SalesPeriodId { get; set; }

    public long EmployeeId { get; set; }

    public int Amount { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual SalesPeriod SalesPeriod { get; set; }
}