// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class Employee
{
    public long Id { get; set; }

    public string FirstName { get; set; }

    public int Order { get; set; }

    public long? UserId { get; set; }

    public string TelNumber { get; set; }

    public bool HideForAgenda { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long? RecurringAppointmentId { get; set; }

    public int Pin { get; set; }

    public long? AgentId { get; set; }

    public string MobileNumber { get; set; }

    public virtual Agent Agent { get; set; }

    public virtual ICollection<AppointmentCaresponsible> AppointmentCaresponsibles { get; set; } = new List<AppointmentCaresponsible>();

    public virtual ICollection<AppointmentSalesResponsible> AppointmentSalesResponsibles { get; set; } = new List<AppointmentSalesResponsible>();

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual ICollection<BiEmployeeDailyBarcodeResult> BiEmployeeDailyBarcodeResults { get; set; } = new List<BiEmployeeDailyBarcodeResult>();

    public virtual ICollection<BiEmployeeDailyGeneralResult> BiEmployeeDailyGeneralResults { get; set; } = new List<BiEmployeeDailyGeneralResult>();

    public virtual ICollection<BiEmployeeDailyGroupResult> BiEmployeeDailyGroupResults { get; set; } = new List<BiEmployeeDailyGroupResult>();

    public virtual ICollection<BiEmployeeDailyGroupSeasonResult> BiEmployeeDailyGroupSeasonResults { get; set; } = new List<BiEmployeeDailyGroupSeasonResult>();

    public virtual ICollection<CollectionDelivery> CollectionDeliveryEmployees { get; set; } = new List<CollectionDelivery>();

    public virtual ICollection<CollectionDelivery> CollectionDeliverySalesEmployees { get; set; } = new List<CollectionDelivery>();

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual ICollection<DedicatedSalesRule> DedicatedSalesRules { get; set; } = new List<DedicatedSalesRule>();

    public virtual ICollection<Document> Documents { get; set; } = new List<Document>();

    public virtual ICollection<EmployeeSeasonalCost> EmployeeSeasonalCosts { get; set; } = new List<EmployeeSeasonalCost>();

    public virtual ICollection<PosDocumentLine> PosDocumentLines { get; set; } = new List<PosDocumentLine>();

    public virtual ICollection<PosSession> PosSessionEmployeeCloseds { get; set; } = new List<PosSession>();

    public virtual ICollection<PosSession> PosSessionEmployees { get; set; } = new List<PosSession>();

    public virtual RecurringAppointment RecurringAppointment { get; set; }

    public virtual ICollection<SalesCondition> SalesConditionCaresponsibles { get; set; } = new List<SalesCondition>();

    public virtual ICollection<SalesCondition> SalesConditionCustomerServiceResponsibles { get; set; } = new List<SalesCondition>();

    public virtual ICollection<SalesConditionEmployee> SalesConditionEmployees { get; set; } = new List<SalesConditionEmployee>();

    public virtual ICollection<Supplier> Suppliers { get; set; } = new List<Supplier>();

    public virtual ICollection<ToDo> ToDos { get; set; } = new List<ToDo>();

    public virtual User User { get; set; }

    public virtual User UserCreated { get; set; }

    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();
}