// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class EnemyRule
{
    public long Id { get; set; }

    public long CustomerId { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Rule IdNavigation { get; set; }
}