// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class Expense
{
    public long Id { get; set; }

    public string Supplier { get; set; }

    public string InvoiceNr { get; set; }

    public decimal TotalAmount { get; set; }

    public decimal AmountPaid { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long PosId { get; set; }

    public long ExpenseTypeId { get; set; }

    public long? InvoiceDocumentId { get; set; }

    public DateTime Date { get; set; }

    public virtual ICollection<ExpenseOpiPrintRequest> ExpenseOpiPrintRequests { get; set; } = new List<ExpenseOpiPrintRequest>();

    public virtual ExpenseType ExpenseType { get; set; }

    public virtual FashionDocument InvoiceDocument { get; set; }

    public virtual Po Pos { get; set; }

    public virtual ICollection<PosSession> PosSessionClosingDifferenceExpenses { get; set; } = new List<PosSession>();

    public virtual ICollection<PosSession> PosSessionOpeningDifferenceExpenses { get; set; } = new List<PosSession>();

    public virtual User UserCreated { get; set; }
}