// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class ExpenseOpiPrintRequest
{
    public long Id { get; set; }

    public string XmlData { get; set; }

    public long ExpenseId { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual Expense Expense { get; set; }

    public virtual User UserCreated { get; set; }
}