// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class ExternalSalesPlatform
{
    public long Id { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long StockLocationId { get; set; }

    public string ApiKey { get; set; }

    public virtual ICollection<ExternalSalesPlatformFashionProductColor> ExternalSalesPlatformFashionProductColors { get; set; } = new List<ExternalSalesPlatformFashionProductColor>();

    public virtual ICollection<ExternalSalesPlatformStockSyncLog> ExternalSalesPlatformStockSyncLogs { get; set; } = new List<ExternalSalesPlatformStockSyncLog>();

    public virtual StockLocation StockLocation { get; set; }

    public virtual User UserCreated { get; set; }

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}