// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class ExternalPosAccountingCodeMap
{
    public long Id { get; set; }

    public long ExternalPosId { get; set; }

    public long PosAccountingCodeId { get; set; }

    public virtual ExternalPo ExternalPos { get; set; }

    public virtual PosAccountingCode PosAccountingCode { get; set; }
}