// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class ExternalSalesPlatformFashionProductColor
{
    public long Id { get; set; }

    public long FashionProductColorId { get; set; }

    public long ExternalSalesPlatformId { get; set; }

    public bool IsOnline { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public bool IsCreated { get; set; }

    public string FarfetchItemId { get; set; }

    public bool FfitemIdViaFf { get; set; }

    public bool FfitemIdViaGoogle { get; set; }

    public bool NotFound { get; set; }

    public virtual ExternalSalesPlatform ExternalSalesPlatform { get; set; }

    public virtual FashionProductColor FashionProductColor { get; set; }

    public virtual User UserCreated { get; set; }
}