// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class ExternalPosJournalEntry
{
    public long Id { get; set; }

    public long ExternalPosJournalId { get; set; }

    public long ExternalPosJournalEntryTypeId { get; set; }

    public decimal Amount { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual ExternalPosJournal ExternalPosJournal { get; set; }

    public virtual ExternalPosJournalEntryType ExternalPosJournalEntryType { get; set; }

    public virtual User UserCreated { get; set; }
}