// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class ExternalPosJournalEntryType
{
    public long Id { get; set; }

    public int Key { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual ICollection<ExternalPosJournalEntry> ExternalPosJournalEntries { get; set; } = new List<ExternalPosJournalEntry>();

    public virtual User UserCreated { get; set; }

    public virtual ICollection<ExternalPo> ExternalPos { get; set; } = new List<ExternalPo>();
}