// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class ExternalDataImportBatch
{
    public long Id { get; set; }

    public long SupplierId { get; set; }

    public long ExternalDataImportBatchTypeId { get; set; }

    public long ExternalDataImportBatchScheduleId { get; set; }

    public long SalesPeriodId { get; set; }

    public DateTime? NextScheduledRun { get; set; }

    public DateTime? LastRun { get; set; }

    public long? LastRunStatusId { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual ICollection<ExternalDataImportBatchLog> ExternalDataImportBatchLogs { get; set; } = new List<ExternalDataImportBatchLog>();

    public virtual ExternalDataImportBatchSchedule ExternalDataImportBatchSchedule { get; set; }

    public virtual ExternalDataImportType ExternalDataImportBatchType { get; set; }

    public virtual ExternalDataImportBatchStatus LastRunStatus { get; set; }

    public virtual Supplier Supplier { get; set; }

    public virtual User UserCreated { get; set; }
}