// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class ExternalPo
{
    public long Id { get; set; }

    public long UserId { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public int ExternalPosTypeId { get; set; }

    public virtual ICollection<ExternalPosAccountingCodeMap> ExternalPosAccountingCodeMaps { get; set; } = new List<ExternalPosAccountingCodeMap>();

    public virtual ICollection<ExternalPosJournal> ExternalPosJournals { get; set; } = new List<ExternalPosJournal>();

    public virtual ICollection<PosAccountingSession> PosAccountingSessions { get; set; } = new List<PosAccountingSession>();

    public virtual ICollection<Target> Targets { get; set; } = new List<Target>();

    public virtual User UserCreated { get; set; }

    public virtual ICollection<ExternalPosJournalEntryType> ExternalPosJournalEntryTypes { get; set; } = new List<ExternalPosJournalEntryType>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}