// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class FashionProductSize
{
    public long Id { get; set; }

    public long SizeId { get; set; }

    public long FashionProductId { get; set; }

    public long VatId { get; set; }

    public decimal ListPrice { get; set; }

    public decimal PurchasePrice { get; set; }

    public decimal WholesalePrice { get; set; }

    public decimal RetailPrice { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public decimal OutletPrice { get; set; }

    public virtual ICollection<FashionBarcode> FashionBarcodes { get; set; } = new List<FashionBarcode>();

    public virtual FashionProduct FashionProduct { get; set; }

    public virtual ICollection<FashionProductSizeRegion> FashionProductSizeRegions { get; set; } = new List<FashionProductSizeRegion>();

    public virtual Size Size { get; set; }

    public virtual User UserCreated { get; set; }

    public virtual Vat Vat { get; set; }
}