// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class FashionDocumentShop
{
    public long Id { get; set; }

    public long ShopId { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long FashionDocumentId { get; set; }

    public virtual FashionDocument FashionDocument { get; set; }

    public virtual Shop Shop { get; set; }

    public virtual User UserCreated { get; set; }
}