// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class FashionProductSizePack
{
    public long Id { get; set; }

    public long SizePackId { get; set; }

    public long FashionProductId { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual FashionProduct FashionProduct { get; set; }

    public virtual SizePack SizePack { get; set; }

    public virtual User UserCreated { get; set; }
}