// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class FashionBarcode
{
    public long Id { get; set; }

    public long FashionProductSizeId { get; set; }

    public long ColorId { get; set; }

    public string Ean13 { get; set; }

    public virtual Color Color { get; set; }

    public virtual FashionProductSize FashionProductSize { get; set; }

    public virtual Barcode IdNavigation { get; set; }
}