// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class FashionProduct
{
    public long Id { get; set; }

    public string ProductCode { get; set; }

    public string ProductName { get; set; }

    public string ModelCode { get; set; }

    public string ModelName { get; set; }

    public string WashingCode { get; set; }

    public string WashingName { get; set; }

    public string FabricCode { get; set; }

    public string FabricName { get; set; }

    public long ProductLineDeliveryId { get; set; }

    public long SalesPeriodId { get; set; }

    public string ProductDescription { get; set; }

    public string ProductLongDescription { get; set; }

    public string ModelDescription { get; set; }

    public string WashingDescription { get; set; }

    public string FabricDescription { get; set; }

    public string MetaData { get; set; }

    public string Origin { get; set; }

    public bool ApplyLowestPrice { get; set; }

    public long? OriginalSalesPeriodId { get; set; }

    public long? NosCoTypeId { get; set; }

    public string Title { get; set; }

    public string ProductLongDescriptionNl { get; set; }

    public string ProductLongDescriptionFr { get; set; }

    public string TitleNl { get; set; }

    public string TitleFr { get; set; }

    public virtual ICollection<DiscountCampaignLineDetail> DiscountCampaignLineDetails { get; set; } = new List<DiscountCampaignLineDetail>();

    public virtual ICollection<FashionProductColor> FashionProductColors { get; set; } = new List<FashionProductColor>();

    public virtual ICollection<FashionProductPicture> FashionProductPictures { get; set; } = new List<FashionProductPicture>();

    public virtual ICollection<FashionProductSizePack> FashionProductSizePacks { get; set; } = new List<FashionProductSizePack>();

    public virtual ICollection<FashionProductSize> FashionProductSizes { get; set; } = new List<FashionProductSize>();

    public virtual Product IdNavigation { get; set; }

    public virtual NosCoType NosCoType { get; set; }

    public virtual SalesPeriod OriginalSalesPeriod { get; set; }

    public virtual ProductLineDelivery ProductLineDelivery { get; set; }

    public virtual SalesPeriod SalesPeriod { get; set; }
}