// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class FashionProductColor
{
    public long Id { get; set; }

    public long ColorId { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long FashionProductId { get; set; }

    public bool IsCancelled { get; set; }

    public bool IsB2c { get; set; }

    public string Sku { get; set; }

    public string WebColor { get; set; }

    public virtual Color Color { get; set; }

    public virtual ICollection<ExternalSalesPlatformFashionProductColor> ExternalSalesPlatformFashionProductColors { get; set; } = new List<ExternalSalesPlatformFashionProductColor>();

    public virtual FashionProduct FashionProduct { get; set; }

    public virtual ICollection<ShopifyFashionProductColor> ShopifyFashionProductColors { get; set; } = new List<ShopifyFashionProductColor>();

    public virtual User UserCreated { get; set; }
}