// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class FashionReturnDocument
{
    public long Id { get; set; }

    public long ExternalReturnReasonId { get; set; }

    public long? InternalReturnReasonId { get; set; }

    public long? ReturnDestionationId { get; set; }

    public long? ReturnApprovedStateId { get; set; }

    public string SupplierRef { get; set; }

    public string InvoiceReference { get; set; }

    public long? ReturnSupplierActionId { get; set; }

    public DateTime? ReturnDate { get; set; }

    public decimal? ReturnAmount { get; set; }

    public decimal? ReturnDiscountPercentage { get; set; }

    public string ExternalReturnReasonRemark { get; set; }

    public virtual ReturnReason ExternalReturnReason { get; set; }

    public virtual FashionDocument IdNavigation { get; set; }

    public virtual ReturnReason InternalReturnReason { get; set; }

    public virtual ReturnApprovedState ReturnApprovedState { get; set; }

    public virtual ReturnDestination ReturnDestionation { get; set; }

    public virtual ReturnSupplierAction ReturnSupplierAction { get; set; }

    public virtual ICollection<ReturnTracking> ReturnTrackings { get; set; } = new List<ReturnTracking>();
}