// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class FashionDocument
{
    public long Id { get; set; }

    public long SalesPeriodId { get; set; }

    public long CustomerLegalHistoryId { get; set; }

    public long DeliveryAddressId { get; set; }

    public long? DeliveryMethodId { get; set; }

    public long PaymentConditionId { get; set; }

    public long AccountingCodeId { get; set; }

    public long? FileImportLogId { get; set; }

    public long? PosId { get; set; }

    public long? PublicationId { get; set; }

    public long? LoyaltyVoucherBarcodeId { get; set; }

    public long? PosTicketCancellationReasonId { get; set; }

    public string PosTicketCancellationReasonDescription { get; set; }

    public string BoxNumber { get; set; }

    public bool EmailInvoicingTeam { get; set; }

    public string TransferHash { get; set; }

    public long? SourceShopId { get; set; }

    public long? DestinationShopId { get; set; }

    public virtual AccountingCode AccountingCode { get; set; }

    public virtual CustomerLegalHistory CustomerLegalHistory { get; set; }

    public virtual Contact DeliveryAddress { get; set; }

    public virtual DeliveryMethod DeliveryMethod { get; set; }

    public virtual Shop DestinationShop { get; set; }

    public virtual ICollection<Expense> Expenses { get; set; } = new List<Expense>();

    public virtual ICollection<FashionDocumentPicture> FashionDocumentPictures { get; set; } = new List<FashionDocumentPicture>();

    public virtual ICollection<FashionDocumentShop> FashionDocumentShops { get; set; } = new List<FashionDocumentShop>();

    public virtual FashionReturnDocument FashionReturnDocument { get; set; }

    public virtual FileImportLog FileImportLog { get; set; }

    public virtual Document IdNavigation { get; set; }

    public virtual VoucherBarcode LoyaltyVoucherBarcode { get; set; }

    public virtual PaymentCondition PaymentCondition { get; set; }

    public virtual Po Pos { get; set; }

    public virtual PosTicketCancellationReason PosTicketCancellationReason { get; set; }

    public virtual Publication Publication { get; set; }

    public virtual SalesPeriod SalesPeriod { get; set; }

    public virtual Shop SourceShop { get; set; }
}