// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class FashionProductSizeRegion
{
    public long Id { get; set; }

    public long VatId { get; set; }

    public decimal ListPrice { get; set; }

    public decimal PurchasePrice { get; set; }

    public decimal WholesalePrice { get; set; }

    public decimal RetailPrice { get; set; }

    public long RegionId { get; set; }

    public long FashionProductSizeId { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public decimal OutletPrice { get; set; }

    public long? SalesPeriodId { get; set; }

    public virtual FashionProductSize FashionProductSize { get; set; }

    public virtual Region Region { get; set; }

    public virtual SalesPeriod SalesPeriod { get; set; }

    public virtual User UserCreated { get; set; }

    public virtual Vat Vat { get; set; }
}