// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class FashionDocumentPicture
{
    public long Id { get; set; }

    public long DocumentId { get; set; }

    public long PictureId { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual FashionDocument Document { get; set; }

    public virtual Picture Picture { get; set; }

    public virtual User UserCreated { get; set; }
}