// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class FdiExportSession
{
    public long Id { get; set; }

    public bool IsDexters { get; set; }

    public DateTime Date { get; set; }

    public int SerialNumber { get; set; }

    public long? AccountingSessionId { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public bool IsLjjv { get; set; }

    public virtual AccountingSession AccountingSession { get; set; }

    public virtual ICollection<FdiExportSessionDocument> FdiExportSessionDocuments { get; set; } = new List<FdiExportSessionDocument>();

    public virtual User UserCreated { get; set; }
}