// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class Feature
{
    public long Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public virtual ICollection<CustomerTypeFeature> CustomerTypeFeatures { get; set; } = new List<CustomerTypeFeature>();

    public virtual ICollection<Permission> Permissions { get; set; } = new List<Permission>();
}