// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class FileImportLog
{
    public long Id { get; set; }

    public string FileName { get; set; }

    public string FileInternalReference { get; set; }

    public string Remarks { get; set; }

    public bool IsProcessed { get; set; }

    public DateTime ProcessedDateTime { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long FileImportLogTypeId { get; set; }

    public string InvoiceReference { get; set; }

    public int Status { get; set; }

    public long SupplierId { get; set; }

    public virtual ICollection<FashionDocument> FashionDocuments { get; set; } = new List<FashionDocument>();

    public virtual ICollection<FileImportLogError> FileImportLogErrors { get; set; } = new List<FileImportLogError>();

    public virtual FileImportLogType FileImportLogType { get; set; }

    public virtual ICollection<RecomaticsInvoiceFileImportLog> RecomaticsInvoiceFileImportLogs { get; set; } = new List<RecomaticsInvoiceFileImportLog>();

    public virtual User UserCreated { get; set; }
}