// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class FileImportLogError
{
    public long Id { get; set; }

    public string ErrorMessage { get; set; }

    public string LineContent { get; set; }

    public long LineNumber { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long? FileImportLogErrorTypeId { get; set; }

    public long? FileImportLogId { get; set; }

    public virtual FileImportLog FileImportLog { get; set; }

    public virtual FileImportLogErrorType FileImportLogErrorType { get; set; }

    public virtual User UserCreated { get; set; }
}