// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class FinancialSupervisionByFcRule
{
    public long Id { get; set; }

    public long? SalesPeriodId { get; set; }

    public decimal? CashDiscount { get; set; }

    public decimal? CommercialDiscount { get; set; }

    public long? PaymentConditionId { get; set; }

    public string SpecificCustomerCode { get; set; }

    public long? SupplierId { get; set; }

    public virtual ICollection<FinancialSupervisionByFcRuleProductLineDelivery> FinancialSupervisionByFcRuleProductLineDeliveries { get; set; } = new List<FinancialSupervisionByFcRuleProductLineDelivery>();

    public virtual ICollection<FinancialSupervisionByFcRuleShop> FinancialSupervisionByFcRuleShops { get; set; } = new List<FinancialSupervisionByFcRuleShop>();

    public virtual Rule IdNavigation { get; set; }

    public virtual PaymentCondition PaymentCondition { get; set; }

    public virtual SalesPeriod SalesPeriod { get; set; }

    public virtual Supplier Supplier { get; set; }
}