// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class FreeTextOnInvoiceRule
{
    public long Id { get; set; }

    public long? SalesPeriodId { get; set; }

    public string FreeText { get; set; }

    public long? SupplierId { get; set; }

    public bool IsPoNumber { get; set; }

    public virtual Rule IdNavigation { get; set; }

    public virtual SalesPeriod SalesPeriod { get; set; }

    public virtual Supplier Supplier { get; set; }
}