// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class History
{
    public long Id { get; set; }

    public long RecordId { get; set; }

    public Guid ContextReference { get; set; }

    public string TableName { get; set; }

    public string OriginalValue { get; set; }

    public string NewValue { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual User UserCreated { get; set; }
}