// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class IntraMirrorConfig
{
    public long Id { get; set; }

    public string SendTo { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public string Name { get; set; }

    public string StockLocations { get; set; }

    public virtual ICollection<IntraMirrorProductLineDelivery> IntraMirrorProductLineDeliveries { get; set; } = new List<IntraMirrorProductLineDelivery>();

    public virtual User UserCreated { get; set; }
}