// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class InvitationType
{
    public long Id { get; set; }

    public string BarcodeCharacter { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual ICollection<CollectionSaleSignUp> CollectionSaleSignUps { get; set; } = new List<CollectionSaleSignUp>();

    public virtual User UserCreated { get; set; }
}