// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class Invitation
{
    public long Id { get; set; }

    public long BarcodeId { get; set; }

    public int TimesScanned { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public Guid Key { get; set; }

    public virtual Barcode Barcode { get; set; }

    public virtual CollectionSalesInvitation CollectionSalesInvitation { get; set; }

    public virtual ICollection<CustomerInvitation> CustomerInvitations { get; set; } = new List<CustomerInvitation>();

    public virtual User UserCreated { get; set; }
}