// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class LabelPrinter
{
    public long Id { get; set; }

    public string Address { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual ICollection<LabelPrintJob> LabelPrintJobs { get; set; } = new List<LabelPrintJob>();

    public virtual ICollection<Po> Pos { get; set; } = new List<Po>();

    public virtual User UserCreated { get; set; }
}