// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class LabelPrintJobItem
{
    public long Id { get; set; }

    public long LabelPrintJobId { get; set; }

    public string ZplInput { get; set; }

    public string ProductCode { get; set; }

    public string Size { get; set; }

    public string Color { get; set; }

    public bool Done { get; set; }

    public int Order { get; set; }

    public virtual LabelPrintJob LabelPrintJob { get; set; }
}