// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class LabelPrintJob
{
    public long Id { get; set; }

    public long LabelPrinterId { get; set; }

    public long? DocumentId { get; set; }

    public DateTime? StartedOn { get; set; }

    public DateTime? FinishedOn { get; set; }

    public DateTime? LastActionOn { get; set; }

    public bool Running { get; set; }

    public string Error { get; set; }

    public bool CancellationToken { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual ICollection<LabelPrintJobItem> LabelPrintJobItems { get; set; } = new List<LabelPrintJobItem>();

    public virtual LabelPrinter LabelPrinter { get; set; }

    public virtual User UserCreated { get; set; }
}