// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class LiuJoShopCode
{
    public string ShopCode { get; set; }

    public string ShopName { get; set; }

    public string ShopCity { get; set; }
}