// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class LiuJoConfirmationDetail
{
    public string ModelCode { get; set; }

    public string FabricCode { get; set; }

    public string ColorCode { get; set; }

    public string SizeName { get; set; }

    public string Barcode { get; set; }

    public string Whsprice { get; set; }

    public string ShopCode { get; set; }

    public string Quantity { get; set; }
}