// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class LoyaltyType
{
    public long Id { get; set; }

    public decimal TriggerAmount { get; set; }

    public decimal Percentage { get; set; }

    public bool IsTriggerOnly { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual ICollection<CustomerLoyalty> CustomerLoyalties { get; set; } = new List<CustomerLoyalty>();

    public virtual User UserCreated { get; set; }
}