// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class MailLog
{
    public long Id { get; set; }

    public string From { get; set; }

    public string To { get; set; }

    public string Body { get; set; }

    public string Subject { get; set; }

    public string Operation { get; set; }

    public string TemplateUsed { get; set; }

    public string Error { get; set; }

    public bool ErrorHandeled { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual User UserCreated { get; set; }
}