// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class ManualDocumentTransfer
{
    public long Id { get; set; }

    public long SourceDocumentTypeId { get; set; }

    public long TargetDocumentTypeId { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public bool MergeTargetDocument { get; set; }

    public virtual DocumentType SourceDocumentType { get; set; }

    public virtual DocumentType TargetDocumentType { get; set; }

    public virtual User UserCreated { get; set; }
}