// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class MiscDocumentLine
{
    public long Id { get; set; }

    public string Description { get; set; }

    public long AccountingCodeId { get; set; }

    public virtual AccountingCode AccountingCode { get; set; }

    public virtual DocumentLine IdNavigation { get; set; }
}