// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class MobileDeviceLogin
{
    public long Id { get; set; }

    public string UserName { get; set; }

    public string DeviceId { get; set; }

    public bool Succes { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual User UserCreated { get; set; }
}