// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class Permission
{
    public long RoleId { get; set; }

    public long FeatureId { get; set; }

    public bool IsVisible { get; set; }

    public bool CanSelect { get; set; }

    public bool CanUpdate { get; set; }

    public bool CanExport { get; set; }

    public bool CanPrint { get; set; }

    public bool CanViewAllRegions { get; set; }

    public bool CanViewAllProductLines { get; set; }

    public bool CanOverrideRules { get; set; }

    public long AppId { get; set; }

    public virtual App App { get; set; }

    public virtual Feature Feature { get; set; }

    public virtual Role Role { get; set; }
}