// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class Picture
{
    public long Id { get; set; }

    public byte[] Image { get; set; }

    public DateTime Date { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public string ContentType { get; set; }

    public Guid Key { get; set; }

    public string StorageUrl { get; set; }

    public virtual ICollection<FashionDocumentPicture> FashionDocumentPictures { get; set; } = new List<FashionDocumentPicture>();

    public virtual ICollection<FashionProductPicture> FashionProductPictures { get; set; } = new List<FashionProductPicture>();

    public virtual ICollection<ShopPicture> ShopPictures { get; set; } = new List<ShopPicture>();

    public virtual User UserCreated { get; set; }
}