// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class Po
{
    public long Id { get; set; }

    public long ShopId { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public string Alias { get; set; }

    public bool PrintStandard { get; set; }

    public string AccountNumberPrefix { get; set; }

    public long? StockLocationId { get; set; }

    public bool HasEposPrinter { get; set; }

    public string PrinterUrl { get; set; }

    public string PaperSize { get; set; }

    public string PaymentDeviceIp { get; set; }

    public int PosMode { get; set; }

    public bool BackOffice { get; set; }

    public bool UseOutletPrices { get; set; }

    public long? LabelPrinterId { get; set; }

    public bool ManagerIsSales { get; set; }

    public string KasverkoopAccount { get; set; }

    public string ModificationAccount { get; set; }

    public string InvoiceAccount { get; set; }

    public string ReturnVoucherAccount { get; set; }

    public string GiftVoucherAccount { get; set; }

    public string CashAccount { get; set; }

    public string LoyaltyAccount { get; set; }

    public string CashExpenseAccount { get; set; }

    public string CashExpenseInvoiceAccount { get; set; }

    public string CashDtaxAccount { get; set; }

    public string DifferenceAccount { get; set; }

    public int LoyaltyMode { get; set; }

    public int PrintMode { get; set; }

    public int LineRoundingMode { get; set; }

    public bool UseGdprStoreApp { get; set; }

    public string AccountNumber { get; set; }

    public long? AccountingCodeId { get; set; }

    public bool AutoExportAccountingSession { get; set; }

    public virtual AccountingCode AccountingCode { get; set; }

    public virtual ICollection<DocumentImportMeta> DocumentImportMeta { get; set; } = new List<DocumentImportMeta>();

    public virtual ICollection<Expense> Expenses { get; set; } = new List<Expense>();

    public virtual ICollection<FashionDocument> FashionDocuments { get; set; } = new List<FashionDocument>();

    public virtual LabelPrinter LabelPrinter { get; set; }

    public virtual ICollection<PosAccountingCodeMap> PosAccountingCodeMaps { get; set; } = new List<PosAccountingCodeMap>();

    public virtual ICollection<PosAccountingSession> PosAccountingSessions { get; set; } = new List<PosAccountingSession>();

    public virtual ICollection<PosEjournal> PosEjournals { get; set; } = new List<PosEjournal>();

    public virtual ICollection<PosSession> PosSessions { get; set; } = new List<PosSession>();

    public virtual Shop Shop { get; set; }

    public virtual StockLocation StockLocation { get; set; }

    public virtual User UserCreated { get; set; }
}