// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class PosAccountingCode
{
    public long Id { get; set; }

    public string Code { get; set; }

    public string ShortCode { get; set; }

    public long PosAccountingCodeTypeId { get; set; }

    public string Description { get; set; }

    public long PosAccountId { get; set; }

    public string AnalyticAccountCode { get; set; }

    public virtual ICollection<ExternalPosAccountingCodeMap> ExternalPosAccountingCodeMaps { get; set; } = new List<ExternalPosAccountingCodeMap>();

    public virtual PosAccount PosAccount { get; set; }

    public virtual ICollection<PosAccountingCodeMap> PosAccountingCodeMaps { get; set; } = new List<PosAccountingCodeMap>();

    public virtual PosAccountingCodeType PosAccountingCodeType { get; set; }

    public virtual ICollection<PosAccountingSessionEntry> PosAccountingSessionEntries { get; set; } = new List<PosAccountingSessionEntry>();
}