// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class PosAccountingCodeMap
{
    public long Id { get; set; }

    public long PosId { get; set; }

    public long PosAccountingCodeId { get; set; }

    public virtual Po Pos { get; set; }

    public virtual PosAccountingCode PosAccountingCode { get; set; }
}