// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class PosAccountingCodeType
{
    public long Id { get; set; }

    public string Name { get; set; }

    public int Key { get; set; }

    public virtual ICollection<PosAccountingCode> PosAccountingCodes { get; set; } = new List<PosAccountingCode>();
}