// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class PosAccountingSessionEntry
{
    public long Id { get; set; }

    public long PosAccountingSessionId { get; set; }

    public long PosAccountingCodeId { get; set; }

    public bool IsHeader { get; set; }

    public decimal StartBalance { get; set; }

    public decimal EndBalance { get; set; }

    public DateTime? Date { get; set; }

    public int? SequenceNumber { get; set; }

    public bool Credit { get; set; }

    public decimal Amount { get; set; }

    public string Comment { get; set; }

    public int? AccountType { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public string AnalyticalAccountCode { get; set; }

    public virtual PosAccountingCode PosAccountingCode { get; set; }

    public virtual PosAccountingSession PosAccountingSession { get; set; }

    public virtual User UserCreated { get; set; }
}