// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class PosAccountingSession
{
    public long Id { get; set; }

    public DateTime? ConfirmedOn { get; set; }

    public byte[] TemplateImportFile { get; set; }

    public long? ExternalPosId { get; set; }

    public long? InternalPosId { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public DateTime Date { get; set; }

    public byte[] TemplatePdfFile { get; set; }

    public virtual ExternalPo ExternalPos { get; set; }

    public virtual Po InternalPos { get; set; }

    public virtual ICollection<PosAccountingSessionEntry> PosAccountingSessionEntries { get; set; } = new List<PosAccountingSessionEntry>();

    public virtual User UserCreated { get; set; }
}