// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class PosEjournal
{
    public long Id { get; set; }

    public string XmlData { get; set; }

    public long PosId { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public string ItsrequestId { get; set; }

    public virtual ICollection<DocumentPayment> DocumentPayments { get; set; } = new List<DocumentPayment>();

    public virtual Po Pos { get; set; }

    public virtual User UserCreated { get; set; }
}