// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class PosPinPadLog
{
    public long Id { get; set; }

    public string Level { get; set; }

    public string Body { get; set; }

    public string OriginalMessage { get; set; }

    public string RequestId { get; set; }
}