// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class PosPinPadMessage
{
    public long Id { get; set; }

    public long PosId { get; set; }

    public string RequestId { get; set; }

    public string MessageType { get; set; }

    public string RequestType { get; set; }

    public decimal? Amount { get; set; }

    public DateTime Timestamp { get; set; }

    public string OriginalMessage { get; set; }

    public string OverallResult { get; set; }
}