// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class PrivacyGdprLog
{
    public long Id { get; set; }

    public long PosId { get; set; }

    public string Source { get; set; }

    public string ActionId { get; set; }

    public string DebugInfo { get; set; }

    public string Payload { get; set; }

    public DateTime Timestamp { get; set; }
}