// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class Product
{
    public long Id { get; set; }

    public string Code { get; set; }

    public string SearchName { get; set; }

    public string SearchCode { get; set; }

    public long BarcodeId { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public bool IsCancelled { get; set; }

    public bool IsReturn { get; set; }

    public long? ProductGroupId { get; set; }

    public long? ProductCategoryId { get; set; }

    public long? SupplierId { get; set; }

    public bool IsTemp { get; set; }

    public string Description { get; set; }

    public string SearchDescription { get; set; }

    public string Hscode { get; set; }

    public string HscodeRemark { get; set; }

    public bool IsCarryOver { get; set; }

    public virtual Barcode Barcode { get; set; }

    public virtual FashionProduct FashionProduct { get; set; }

    public virtual ICollection<ProductAlias> ProductAliases { get; set; } = new List<ProductAlias>();

    public virtual ProductCategory ProductCategory { get; set; }

    public virtual ICollection<ProductDeliveryWindow> ProductDeliveryWindows { get; set; } = new List<ProductDeliveryWindow>();

    public virtual ProductGroup ProductGroup { get; set; }

    public virtual ICollection<SalesConditionDiscountExcludedProduct> SalesConditionDiscountExcludedProducts { get; set; } = new List<SalesConditionDiscountExcludedProduct>();

    public virtual Supplier Supplier { get; set; }

    public virtual User UserCreated { get; set; }
}