// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class ProductCategory
{
    public long Id { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long ProductGroupId { get; set; }

    public virtual ICollection<ProductCategoryAlias> ProductCategoryAliases { get; set; } = new List<ProductCategoryAlias>();

    public virtual ProductGroup ProductGroup { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual User UserCreated { get; set; }
}