// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class ProductLineDelivery
{
    public long Id { get; set; }

    public string Code { get; set; }

    public long? SalesPeriodTypeId { get; set; }

    public int SalesTime { get; set; }

    public bool IsInUse { get; set; }

    public long ProductLineId { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public string SupplierReference { get; set; }

    public long? ProductLineDeliveryRelatedId { get; set; }

    public virtual ICollection<ProductLineDelivery> InverseProductLineDeliveryRelated { get; set; } = new List<ProductLineDelivery>();

    public virtual ProductLine ProductLine { get; set; }

    public virtual ProductLineDelivery ProductLineDeliveryRelated { get; set; }

    public virtual SalesPeriodType SalesPeriodType { get; set; }

    public virtual ICollection<ShopDelivery> ShopDeliveries { get; set; } = new List<ShopDelivery>();

    public virtual User UserCreated { get; set; }
}