// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class ProposedRule
{
    public long Id { get; set; }

    public bool IsApproved { get; set; }

    public virtual DelayedDeliveryProposedRule DelayedDeliveryProposedRule { get; set; }

    public virtual Rule IdNavigation { get; set; }
}