// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class Publication
{
    public long Id { get; set; }

    public string Frequency { get; set; }

    public string Function { get; set; }

    public string PublicationType { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual ICollection<FashionDocument> FashionDocuments { get; set; } = new List<FashionDocument>();

    public virtual ICollection<PublicationCountry> PublicationCountries { get; set; } = new List<PublicationCountry>();

    public virtual User UserCreated { get; set; }
}