// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class RecomaticsInvoice
{
    public long Id { get; set; }

    public string FileName { get; set; }

    public string DirectoryName { get; set; }

    public long BatchId { get; set; }

    public DateTime? ScanDate { get; set; }

    public string ScannerName { get; set; }

    public long DocumentId { get; set; }

    public string DocumentType { get; set; }

    public DateTime DocInvoiceDate { get; set; }

    public string Currency { get; set; }

    public string InvoiceRef { get; set; }

    public decimal NetAmount { get; set; }

    public long? SupplierId { get; set; }

    public decimal TotalAmount { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public string Company { get; set; }

    public string InvoiceType { get; set; }

    public string VatSupplier { get; set; }

    public string SupplierCode { get; set; }

    public string InvoiceRefOriginalInvoice { get; set; }

    public string CustomerNumber { get; set; }

    public int ImportType { get; set; }

    public long PartCount { get; set; }

    public bool IsMatch { get; set; }

    public long? SalesPeriodId { get; set; }

    public decimal? PlAmount { get; set; }

    public int? PlQuantity { get; set; }

    public bool IsDeleted { get; set; }

    public string Remarks { get; set; }

    public virtual ICollection<RecomaticsInvoiceCollectionDelivery> RecomaticsInvoiceCollectionDeliveries { get; set; } = new List<RecomaticsInvoiceCollectionDelivery>();

    public virtual ICollection<RecomaticsInvoiceFileImportLog> RecomaticsInvoiceFileImportLogs { get; set; } = new List<RecomaticsInvoiceFileImportLog>();

    public virtual SalesPeriod SalesPeriod { get; set; }

    public virtual Supplier Supplier { get; set; }

    public virtual User UserCreated { get; set; }
}