// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class ReportDefinition
{
    public long Id { get; set; }

    public byte[] Data { get; set; }

    public bool IsStandard { get; set; }

    public long ReportContextId { get; set; }

    public long DepartmentId { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public bool SaveFilter { get; set; }

    public string DefaultFilterJson { get; set; }

    public long? ReportShareId { get; set; }

    public virtual Department Department { get; set; }

    public virtual ReportContext ReportContext { get; set; }

    public virtual ReportShare ReportShare { get; set; }

    public virtual User UserCreated { get; set; }
}