// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class ReportContext
{
    public long Id { get; set; }

    public string Name { get; set; }

    public string FilterType { get; set; }

    public string FilterControlType { get; set; }

    public virtual ICollection<ReportDefinition> ReportDefinitions { get; set; } = new List<ReportDefinition>();
}