// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class ReturnReason
{
    public long Id { get; set; }

    public string NameFr { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public bool IsInternalReason { get; set; }

    public int? SubstractFromDeliveries { get; set; }

    public virtual ICollection<FashionReturnDocument> FashionReturnDocumentExternalReturnReasons { get; set; } = new List<FashionReturnDocument>();

    public virtual ICollection<FashionReturnDocument> FashionReturnDocumentInternalReturnReasons { get; set; } = new List<FashionReturnDocument>();

    public virtual User UserCreated { get; set; }
}