// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class ReturnState
{
    public long Id { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long? ReturnStateActionId { get; set; }

    public string NameFr { get; set; }

    public string InstructionsNl { get; set; }

    public string InstructionsFr { get; set; }

    public virtual ReturnStateAction ReturnStateAction { get; set; }

    public virtual ICollection<ReturnTracking> ReturnTrackings { get; set; } = new List<ReturnTracking>();

    public virtual User UserCreated { get; set; }
}