// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class ReturnRule
{
    public long Id { get; set; }

    public long? BrandId { get; set; }

    public long SalesPeriodId { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public decimal? MinAmount { get; set; }

    public decimal? MaxAmount { get; set; }

    public decimal Decimal { get; set; }

    public bool SwapRequired { get; set; }

    public long? SupplierId { get; set; }

    public virtual Brand Brand { get; set; }

    public virtual Rule IdNavigation { get; set; }

    public virtual SalesPeriod SalesPeriod { get; set; }

    public virtual Supplier Supplier { get; set; }
}