// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class ReturnTracking
{
    public long Id { get; set; }

    public long ReturnStateId { get; set; }

    public bool IsCustomerTracking { get; set; }

    public string ActionResult { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long? FashionReturnDocumentId { get; set; }

    public virtual FashionReturnDocument FashionReturnDocument { get; set; }

    public virtual ReturnState ReturnState { get; set; }

    public virtual User UserCreated { get; set; }
}