// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class RoadAppointmentProductLine
{
    public long Id { get; set; }

    public long ProductLineId { get; set; }

    public long SalesPeriodId { get; set; }

    public long ShowroomAppointmentId { get; set; }

    public long? ShowroomAppointmentSalesConditionSellOutId { get; set; }

    public long? ShowroomAppointmentSalesConditionSellOutReasonId { get; set; }

    public string Remarks { get; set; }

    public string SellOutRemarks { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long? RoadAppointmentId { get; set; }

    public virtual ProductLine ProductLine { get; set; }

    public virtual RoadAppointment RoadAppointment { get; set; }

    public virtual SalesPeriod SalesPeriod { get; set; }

    public virtual ShowroomAppointment ShowroomAppointment { get; set; }

    public virtual ShowroomAppointmentSalesConditionSellOut ShowroomAppointmentSalesConditionSellOut { get; set; }

    public virtual ShowroomAppointmentSalesConditionReason ShowroomAppointmentSalesConditionSellOutReason { get; set; }

    public virtual User UserCreated { get; set; }
}