// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class RoadAppointment
{
    public long Id { get; set; }

    public long ShopId { get; set; }

    public virtual Appointment IdNavigation { get; set; }

    public virtual ICollection<RoadAppointmentProductLine> RoadAppointmentProductLines { get; set; } = new List<RoadAppointmentProductLine>();

    public virtual Shop Shop { get; set; }
}