// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class Rule
{
    public long Id { get; set; }

    public string Remarks { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public string Summary { get; set; }

    public int? TempOriginalRuleId { get; set; }

    public virtual CustomerBlockedRule CustomerBlockedRule { get; set; }

    public virtual ICollection<CustomerRule> CustomerRules { get; set; } = new List<CustomerRule>();

    public virtual DedicatedSalesRule DedicatedSalesRule { get; set; }

    public virtual DelayedDeliveryRule DelayedDeliveryRule { get; set; }

    public virtual DeliveryRemarksRule DeliveryRemarksRule { get; set; }

    public virtual DiscountRuleRule DiscountRuleRule { get; set; }

    public virtual ICollection<DocumentRule> DocumentRules { get; set; } = new List<DocumentRule>();

    public virtual EnemyRule EnemyRule { get; set; }

    public virtual FinancialSupervisionByFcRule FinancialSupervisionByFcRule { get; set; }

    public virtual FreeTextOnInvoiceRule FreeTextOnInvoiceRule { get; set; }

    public virtual NoDeliveryRule NoDeliveryRule { get; set; }

    public virtual ProposedRule ProposedRule { get; set; }

    public virtual ReturnRule ReturnRule { get; set; }

    public virtual SuspendedDeliveryRule SuspendedDeliveryRule { get; set; }

    public virtual TimeframeDifferenceRule TimeframeDifferenceRule { get; set; }

    public virtual User UserCreated { get; set; }
}