// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class SalesCondition
{
    public long Id { get; set; }

    public long SupplierId { get; set; }

    public long ProductLineDeliveryId { get; set; }

    public long DepartmentId { get; set; }

    public long ProductSalesPeriodId { get; set; }

    public long ShowroomSalesPeriodId { get; set; }

    public long SalesConditionTypeId { get; set; }

    public long SalesConditionGroupId { get; set; }

    public bool IsClosed { get; set; }

    public DateTime? ClosingDate { get; set; }

    public DateTime? ArrivalDate { get; set; }

    public DateTime? DepartureDate { get; set; }

    public bool ShowInWebshop { get; set; }

    public decimal? WebshopDiscount { get; set; }

    public bool UpfrontPaymentRequired { get; set; }

    public decimal? MinimumOrderAmount { get; set; }

    public decimal? DeliveryPercentage { get; set; }

    public decimal? MarginPercentage { get; set; }

    public decimal? PurchasePercentage { get; set; }

    public decimal? SamplePercentage { get; set; }

    public decimal? TargetAmount { get; set; }

    public int? TargetQuantity { get; set; }

    public long? SampleDestinationId { get; set; }

    public long? SampleSalesPeriodId { get; set; }

    public long AccountingCodeId { get; set; }

    public string Remarks { get; set; }

    public long SalesConditionPeriodId { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long? ProductMatrixId { get; set; }

    public long? DocumentFlowId { get; set; }

    public DateTime? SwapStartDate { get; set; }

    public DateTime? SwapEndDate { get; set; }

    public string Alias { get; set; }

    public decimal? CollectionSaleStockMarkup { get; set; }

    public decimal? Markup { get; set; }

    public int BonusBudget { get; set; }

    public bool BonusActive { get; set; }

    public int? Forecast1 { get; set; }

    public int? Forecast2 { get; set; }

    public int? Forecast3 { get; set; }

    public int? Forecast4 { get; set; }

    public int? Forecast1IncMono { get; set; }

    public int? Forecast2IncMono { get; set; }

    public int? Forecast3IncMono { get; set; }

    public int? Forecast4IncMono { get; set; }

    public bool UseBonus { get; set; }

    public long? CustomerServiceResponsibleId { get; set; }

    public long? CaresponsibleId { get; set; }

    public bool ShowOnB2c { get; set; }

    public DateTime? FinalClosingDate { get; set; }

    public bool UpdatePurchasePriceOnInvoicing { get; set; }

    public string TransportCosts { get; set; }

    public long? AgentId { get; set; }

    public decimal SwapCompensationPercentage { get; set; }

    public bool CanSwap { get; set; }

    public string TransportAccountcodeSupplier { get; set; }

    public bool IsLiuJo { get; set; }

    public virtual AccountingCode AccountingCode { get; set; }

    public virtual ICollection<AdvancedPayment> AdvancedPayments { get; set; } = new List<AdvancedPayment>();

    public virtual Agent Agent { get; set; }

    public virtual Employee Caresponsible { get; set; }

    public virtual Employee CustomerServiceResponsible { get; set; }

    public virtual Department Department { get; set; }

    public virtual DocumentFlow DocumentFlow { get; set; }

    public virtual ProductLineDelivery ProductLineDelivery { get; set; }

    public virtual ProductMatrix ProductMatrix { get; set; }

    public virtual SalesPeriod ProductSalesPeriod { get; set; }

    public virtual ICollection<SalesConditionDiscount> SalesConditionDiscounts { get; set; } = new List<SalesConditionDiscount>();

    public virtual ICollection<SalesConditionEmployee> SalesConditionEmployees { get; set; } = new List<SalesConditionEmployee>();

    public virtual SalesConditionGroup SalesConditionGroup { get; set; }

    public virtual SalesConditionPeriod SalesConditionPeriod { get; set; }

    public virtual ICollection<SalesConditionPlanning> SalesConditionPlannings { get; set; } = new List<SalesConditionPlanning>();

    public virtual SalesConditionType SalesConditionType { get; set; }

    public virtual SampleDestination SampleDestination { get; set; }

    public virtual SalesPeriod SampleSalesPeriod { get; set; }

    public virtual ICollection<ShowroomAppointmentSalesCondition> ShowroomAppointmentSalesConditions { get; set; } = new List<ShowroomAppointmentSalesCondition>();

    public virtual SalesPeriod ShowroomSalesPeriod { get; set; }

    public virtual Supplier Supplier { get; set; }

    public virtual User UserCreated { get; set; }
}