// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class SalesConditionPlanning
{
    public long Id { get; set; }

    public DateTime AppointmentStartDate { get; set; }

    public DateTime AppointmentStopDate { get; set; }

    public DateTime? DeliveryStartDate { get; set; }

    public DateTime? DeliveryStopDate { get; set; }

    public DateTime? AcceptDeliveryUntilDate { get; set; }

    public long SalesConditionId { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual SalesCondition SalesCondition { get; set; }

    public virtual ICollection<SalesConditionShowroom> SalesConditionShowrooms { get; set; } = new List<SalesConditionShowroom>();

    public virtual User UserCreated { get; set; }
}