// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class SalesConditionDiscount
{
    public long Id { get; set; }

    public long SalesConditionId { get; set; }

    public decimal DiscountPercentage { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual SalesCondition SalesCondition { get; set; }

    public virtual ICollection<SalesConditionDiscountExcludedProduct> SalesConditionDiscountExcludedProducts { get; set; } = new List<SalesConditionDiscountExcludedProduct>();

    public virtual User UserCreated { get; set; }
}