// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class SalesPeriod
{
    public long Id { get; set; }

    public string ShortCode { get; set; }

    public string Code { get; set; }

    public DateTime BeginDate { get; set; }

    public DateTime EndDate { get; set; }

    public decimal TransportCost { get; set; }

    public decimal TransportCostLimit { get; set; }

    public int InflationPercentage { get; set; }

    public long SalesPeriodTypeId { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public bool ShowInWebshop { get; set; }

    public DateTime? DeliveryBeginDate { get; set; }

    public DateTime? DeliveryEndDate { get; set; }

    public string WpsCode { get; set; }

    public string WpsYear { get; set; }

    public DateTime? LendingPeriodEndDate { get; set; }

    public bool ShopifySales { get; set; }

    public virtual SalesPeriodType SalesPeriodType { get; set; }

    public virtual ICollection<ShopDelivery> ShopDeliveries { get; set; } = new List<ShopDelivery>();

    public virtual User UserCreated { get; set; }
}