// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class SalesConditionShowroom
{
    public long Id { get; set; }

    public long ShowroomId { get; set; }

    public int Percent { get; set; }

    public long SalesConditionPlanningId { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public int SimultaneousSales { get; set; }

    public int Surface { get; set; }

    public virtual SalesConditionPlanning SalesConditionPlanning { get; set; }

    public virtual Showroom Showroom { get; set; }

    public virtual User UserCreated { get; set; }
}