// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class ShopDeliveryState
{
    public long Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public bool IsCustomer { get; set; }

    public virtual ICollection<ShopDelivery> ShopDeliveries { get; set; } = new List<ShopDelivery>();

    public virtual User UserCreated { get; set; }
}