// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class Shop
{
    public long Id { get; set; }

    public DateTime? OpeningDate { get; set; }

    public int? Area { get; set; }

    public int? SalesPeople { get; set; }

    public int? DisplayWindows { get; set; }

    public int? Floors { get; set; }

    public long? ShopTypeId { get; set; }

    public long? SpancoId { get; set; }

    public long? ContactId { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public string SearchName { get; set; }

    public bool IsParallelSales { get; set; }

    public virtual ICollection<AppointmentSalesResponsible> AppointmentSalesResponsibles { get; set; } = new List<AppointmentSalesResponsible>();

    public virtual Contact Contact { get; set; }

    public virtual ICollection<CustomerShop> CustomerShops { get; set; } = new List<CustomerShop>();

    public virtual ICollection<DelayedDeliveryProposedRuleShop> DelayedDeliveryProposedRuleShops { get; set; } = new List<DelayedDeliveryProposedRuleShop>();

    public virtual ICollection<DelayedDeliveryRuleShop> DelayedDeliveryRuleShops { get; set; } = new List<DelayedDeliveryRuleShop>();

    public virtual ICollection<DeliveryRemarksRuleShop> DeliveryRemarksRuleShops { get; set; } = new List<DeliveryRemarksRuleShop>();

    public virtual ICollection<DiscountCampaignLine> DiscountCampaignLines { get; set; } = new List<DiscountCampaignLine>();

    public virtual ICollection<FashionDocument> FashionDocumentDestinationShops { get; set; } = new List<FashionDocument>();

    public virtual ICollection<FashionDocumentShop> FashionDocumentShops { get; set; } = new List<FashionDocumentShop>();

    public virtual ICollection<FashionDocument> FashionDocumentSourceShops { get; set; } = new List<FashionDocument>();

    public virtual ICollection<FinancialSupervisionByFcRuleShop> FinancialSupervisionByFcRuleShops { get; set; } = new List<FinancialSupervisionByFcRuleShop>();

    public virtual ICollection<FreeTextOnInvoiceRuleShop> FreeTextOnInvoiceRuleShops { get; set; } = new List<FreeTextOnInvoiceRuleShop>();

    public virtual ICollection<KlaviyoShopSync> KlaviyoShopSyncs { get; set; } = new List<KlaviyoShopSync>();

    public virtual ICollection<Po> Pos { get; set; } = new List<Po>();

    public virtual ICollection<Prospection> Prospections { get; set; } = new List<Prospection>();

    public virtual ICollection<RoadAppointment> RoadAppointments { get; set; } = new List<RoadAppointment>();

    public virtual ICollection<ShopAgeCategory> ShopAgeCategories { get; set; } = new List<ShopAgeCategory>();

    public virtual ICollection<ShopAvailability> ShopAvailabilities { get; set; } = new List<ShopAvailability>();

    public virtual ICollection<ShopCommercialLocation> ShopCommercialLocations { get; set; } = new List<ShopCommercialLocation>();

    public virtual ICollection<ShopCompetitorBrand> ShopCompetitorBrands { get; set; } = new List<ShopCompetitorBrand>();

    public virtual ICollection<ShopCompetitorProductLine> ShopCompetitorProductLines { get; set; } = new List<ShopCompetitorProductLine>();

    public virtual ICollection<ShopContact> ShopContacts { get; set; } = new List<ShopContact>();

    public virtual ICollection<ShopDelivery> ShopDeliveries { get; set; } = new List<ShopDelivery>();

    public virtual ICollection<ShopGender> ShopGenders { get; set; } = new List<ShopGender>();

    public virtual ICollection<ShopLine> ShopLines { get; set; } = new List<ShopLine>();

    public virtual ICollection<ShopPicture> ShopPictures { get; set; } = new List<ShopPicture>();

    public virtual ICollection<ShopSegmentType> ShopSegmentTypes { get; set; } = new List<ShopSegmentType>();

    public virtual ICollection<ShopSupplierCode> ShopSupplierCodes { get; set; } = new List<ShopSupplierCode>();

    public virtual ShopType ShopType { get; set; }

    public virtual ICollection<ShopVisit> ShopVisits { get; set; } = new List<ShopVisit>();

    public virtual ICollection<ShowroomAppointmentSalesConditionShop> ShowroomAppointmentSalesConditionShops { get; set; } = new List<ShowroomAppointmentSalesConditionShop>();

    public virtual Spanco Spanco { get; set; }

    public virtual User UserCreated { get; set; }
}