// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace FCentricProspections.Server.DataModels;

public partial class Shop
{
    public long Id { get; set; }

    public DateTime? OpeningDate { get; set; }

    public int? Area { get; set; }

    public int? SalesPeople { get; set; }

    public int? DisplayWindows { get; set; }

    public int? Floors { get; set; }

    public long? ShopTypeId { get; set; }

    public long? SpancoId { get; set; }

    public long? ContactId { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    [Timestamp]
    public byte[] Timestamp { get; set; }

    public string SearchName { get; set; }

    public bool IsParallelSales { get; set; }

    public virtual Contact Contact { get; set; }

    public virtual ICollection<CustomerShop> CustomerShops { get; set; } = new List<CustomerShop>();

    public virtual ICollection<Prospection> Prospections { get; set; } = new List<Prospection>();

    public virtual ICollection<ShopContact> ShopContacts { get; set; } = new List<ShopContact>();

    public virtual ICollection<ShopDelivery> ShopDeliveries { get; set; } = new List<ShopDelivery>();

    public virtual User UserCreated { get; set; }
}