// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class ShopAvailability
{
    public long AvailabilityTypeId { get; set; }

    public long AvailabilityDayId { get; set; }

    public long ShopId { get; set; }

    public virtual AvailabilityDay AvailabilityDay { get; set; }

    public virtual AvailabilityType AvailabilityType { get; set; }

    public virtual Shop Shop { get; set; }
}