// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class ShopifyFashionProductColor
{
    public long Id { get; set; }

    public long FashionProductColorId { get; set; }

    public bool IsOnline { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public DateTime? FarfetchScrapeDate { get; set; }

    public long? ShopifyId { get; set; }

    public bool IsExcludedFromSale { get; set; }

    public virtual FashionProductColor FashionProductColor { get; set; }

    public virtual User UserCreated { get; set; }
}