// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class ShowroomAppointmentSalesConditionSigning
{
    public long Id { get; set; }

    public long ShowroomAppointmentSalesConditionId { get; set; }

    public bool OrderIsSigned { get; set; }

    public long? OrderUnsignedReasonId { get; set; }

    public string OrderRemarks { get; set; }

    public bool ContractIsSigned { get; set; }

    public long? ContractUnsignedReasonId { get; set; }

    public string ContractRemarks { get; set; }

    public bool PrepaymentIsSigned { get; set; }

    public long? PrepaymentUnsignedReasonId { get; set; }

    public string PrepaymentRemarks { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual ShowroomAppointmentSalesConditionUnsignedReason ContractUnsignedReason { get; set; }

    public virtual ShowroomAppointmentSalesCondition IdNavigation { get; set; }

    public virtual ShowroomAppointmentSalesConditionUnsignedReason OrderUnsignedReason { get; set; }

    public virtual ShowroomAppointmentSalesConditionUnsignedReason PrepaymentUnsignedReason { get; set; }

    public virtual User UserCreated { get; set; }
}