// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class ShowroomAppointmentSalesConditionShop
{
    public long Id { get; set; }

    public long ShopId { get; set; }

    public long ShowroomAppointmentSalesConditionId { get; set; }

    public long? ShowroomAppointmentSalesConditionShopActionId { get; set; }

    public string Remarks { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public decimal? OrderAmount { get; set; }

    public int? OrderQuantity { get; set; }

    public bool IsUpdated { get; set; }

    public string OrderNr { get; set; }

    public virtual Shop Shop { get; set; }

    public virtual ShowroomAppointmentSalesCondition ShowroomAppointmentSalesCondition { get; set; }

    public virtual ShowroomAppointmentSalesConditionShopAction ShowroomAppointmentSalesConditionShopAction { get; set; }

    public virtual User UserCreated { get; set; }
}