// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class ShowroomAppointmentSalesCondition
{
    public long Id { get; set; }

    public long SalesConditionId { get; set; }

    public long ShowroomAppointmentId { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long? ShowroomAppointmentSalesConditionReasonId { get; set; }

    public long? ShowroomAppointmentSalesConditionResponseId { get; set; }

    public long? ShowroomAppointmentSalesConditionSellOutId { get; set; }

    public string Remarks { get; set; }

    public string SellOutRemarks { get; set; }

    public long? ShowroomAppointmentSalesConditionSellOutReasonId { get; set; }

    public long? ContractStateId { get; set; }

    public long? UpfrontPaymentContractStateId { get; set; }

    public string PoNumber { get; set; }

    public long? ShowroomAppointmentSalesConditionSigningId { get; set; }

    public bool IsLiuJo { get; set; }

    public virtual ContractState ContractState { get; set; }

    public virtual SalesCondition SalesCondition { get; set; }

    public virtual ShowroomAppointment ShowroomAppointment { get; set; }

    public virtual ShowroomAppointmentSalesConditionReason ShowroomAppointmentSalesConditionReason { get; set; }

    public virtual ShowroomAppointmentSalesConditionResponse ShowroomAppointmentSalesConditionResponse { get; set; }

    public virtual ShowroomAppointmentSalesConditionSellOut ShowroomAppointmentSalesConditionSellOut { get; set; }

    public virtual ShowroomAppointmentSalesConditionReason ShowroomAppointmentSalesConditionSellOutReason { get; set; }

    public virtual ICollection<ShowroomAppointmentSalesConditionShop> ShowroomAppointmentSalesConditionShops { get; set; } = new List<ShowroomAppointmentSalesConditionShop>();

    public virtual ShowroomAppointmentSalesConditionSigning ShowroomAppointmentSalesConditionSigning { get; set; }

    public virtual ContractState UpfrontPaymentContractState { get; set; }

    public virtual User UserCreated { get; set; }
}