// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class ShowroomAppointment
{
    public long Id { get; set; }

    public long? ShowroomId { get; set; }

    public bool IsInfo { get; set; }

    public DateTime? SchedaEnteredDate { get; set; }

    public virtual Appointment IdNavigation { get; set; }

    public virtual ICollection<RoadAppointmentProductLine> RoadAppointmentProductLines { get; set; } = new List<RoadAppointmentProductLine>();

    public virtual Showroom Showroom { get; set; }

    public virtual ICollection<ShowroomAppointmentSalesCondition> ShowroomAppointmentSalesConditions { get; set; } = new List<ShowroomAppointmentSalesCondition>();
}