// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class ShowroomAppointmentSalesConditionUnsignedReason
{
    public long Id { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual ICollection<ShowroomAppointmentSalesConditionSigning> ShowroomAppointmentSalesConditionSigningContractUnsignedReasons { get; set; } = new List<ShowroomAppointmentSalesConditionSigning>();

    public virtual ICollection<ShowroomAppointmentSalesConditionSigning> ShowroomAppointmentSalesConditionSigningOrderUnsignedReasons { get; set; } = new List<ShowroomAppointmentSalesConditionSigning>();

    public virtual ICollection<ShowroomAppointmentSalesConditionSigning> ShowroomAppointmentSalesConditionSigningPrepaymentUnsignedReasons { get; set; } = new List<ShowroomAppointmentSalesConditionSigning>();

    public virtual User UserCreated { get; set; }
}