// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class ShowroomAppointmentSalesConditionReason
{
    public long Id { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual ICollection<RoadAppointmentProductLine> RoadAppointmentProductLines { get; set; } = new List<RoadAppointmentProductLine>();

    public virtual ICollection<ShowroomAppointmentSalesCondition> ShowroomAppointmentSalesConditionShowroomAppointmentSalesConditionReasons { get; set; } = new List<ShowroomAppointmentSalesCondition>();

    public virtual ICollection<ShowroomAppointmentSalesCondition> ShowroomAppointmentSalesConditionShowroomAppointmentSalesConditionSellOutReasons { get; set; } = new List<ShowroomAppointmentSalesCondition>();

    public virtual User UserCreated { get; set; }
}