// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class Size
{
    public long Id { get; set; }

    public long SizeScaleId { get; set; }

    public int Order { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual ICollection<FashionProductSize> FashionProductSizes { get; set; } = new List<FashionProductSize>();

    public virtual ICollection<SizePackQuantity> SizePackQuantities { get; set; } = new List<SizePackQuantity>();

    public virtual SizeScale SizeScale { get; set; }

    public virtual User UserCreated { get; set; }
}