// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class SizeScale
{
    public long Id { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public bool ShowInWebshop { get; set; }

    public long? SizeTypeId { get; set; }

    public virtual SizeType SizeType { get; set; }

    public virtual ICollection<Size> Sizes { get; set; } = new List<Size>();

    public virtual User UserCreated { get; set; }
}