// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class SizePack
{
    public long Id { get; set; }

    public string Code { get; set; }

    public long SalesPeriodId { get; set; }

    public long SupplierId { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual ICollection<DocumentLine> DocumentLines { get; set; } = new List<DocumentLine>();

    public virtual ICollection<FashionProductSizePack> FashionProductSizePacks { get; set; } = new List<FashionProductSizePack>();

    public virtual SalesPeriod SalesPeriod { get; set; }

    public virtual ICollection<SizePackQuantity> SizePackQuantities { get; set; } = new List<SizePackQuantity>();

    public virtual Supplier Supplier { get; set; }

    public virtual User UserCreated { get; set; }
}