// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class StockLocation
{
    public long Id { get; set; }

    public long ContactId { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public string BarcodePrefix { get; set; }

    public bool ShowOnWebshop { get; set; }

    public bool CanSwap { get; set; }

    public bool ShowOnB2c { get; set; }

    public bool IsOb { get; set; }

    public virtual ICollection<BiShopDailySeasonalBrandResult> BiShopDailySeasonalBrandResults { get; set; } = new List<BiShopDailySeasonalBrandResult>();

    public virtual Contact Contact { get; set; }

    public virtual ICollection<DocumentFlow> DocumentFlows { get; set; } = new List<DocumentFlow>();

    public virtual ICollection<DocumentImportMetaDetail> DocumentImportMetaDetails { get; set; } = new List<DocumentImportMetaDetail>();

    public virtual ICollection<DocumentLine> DocumentLines { get; set; } = new List<DocumentLine>();

    public virtual ICollection<ExternalSalesPlatform> ExternalSalesPlatforms { get; set; } = new List<ExternalSalesPlatform>();

    public virtual ICollection<Po> Pos { get; set; } = new List<Po>();

    public virtual ICollection<ShopDelivery> ShopDeliveries { get; set; } = new List<ShopDelivery>();

    public virtual ICollection<Target> Targets { get; set; } = new List<Target>();

    public virtual User UserCreated { get; set; }
}