// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class Subselect
{
    public long Id { get; set; }

    public string Name { get; set; }

    public string Documenttype { get; set; }

    public long Documenttypeid { get; set; }

    public string Salesperiod { get; set; }

    public long Salesperiodid { get; set; }

    public string Customername { get; set; }

    public long Customerid { get; set; }

    public string Documentstate { get; set; }

    public DateTime Date { get; set; }

    public string Paymentcondition { get; set; }

    public string Brand { get; set; }

    public long Brandid { get; set; }

    public string Accountingcode { get; set; }

    public string Fileimportlog { get; set; }

    public string Vat { get; set; }

    public string Supplier { get; set; }

    public string Documentdeliverystate { get; set; }

    public long Documentdeliverystateid { get; set; }

    public DateTime? Deliverydate { get; set; }

    public decimal? Amount { get; set; }

    public decimal? Purchaseamount { get; set; }

    public int? Quantity { get; set; }

    public int? Restquantity { get; set; }

    public int? Transferquantity { get; set; }

    public decimal? Discount { get; set; }

    public long? Customercodeid { get; set; }

    public string Blockedtype { get; set; }

    public string Upfrontpayment { get; set; }

    public string Postalcode { get; set; }

    public string City { get; set; }

    public string Country { get; set; }

    public string Vatnr { get; set; }

    public string Kvk { get; set; }

    public decimal Rate { get; set; }

    public string Transferedfromname { get; set; }
}