// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class SupplierSalesCondition
{
    public long Id { get; set; }

    public long LanguageId { get; set; }

    public string Content { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long? SupplierId { get; set; }

    public virtual Language Language { get; set; }

    public virtual Supplier Supplier { get; set; }

    public virtual User UserCreated { get; set; }
}