// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class SupplierVat
{
    public long Id { get; set; }

    public long SupplierId { get; set; }

    public long CountryId { get; set; }

    public long VatId { get; set; }

    public string ContractHeader { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long? AccountingCodeId { get; set; }

    public long? ExcludedAccountingCodeId { get; set; }

    public long? BehaccountingCodeId { get; set; }

    public virtual AccountingCode AccountingCode { get; set; }

    public virtual AccountingCode BehaccountingCode { get; set; }

    public virtual Country Country { get; set; }

    public virtual AccountingCode ExcludedAccountingCode { get; set; }

    public virtual Supplier Supplier { get; set; }

    public virtual User UserCreated { get; set; }

    public virtual Vat Vat { get; set; }
}