// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class SupplierMarkup
{
    public long Id { get; set; }

    public long SupplierId { get; set; }

    public long SalesPeriodId { get; set; }

    public long ProductLineDeliveryId { get; set; }

    public long RegionId { get; set; }

    public decimal MarginPercentage { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual ProductLineDelivery ProductLineDelivery { get; set; }

    public virtual Region Region { get; set; }

    public virtual SalesPeriod SalesPeriod { get; set; }

    public virtual Supplier Supplier { get; set; }

    public virtual User UserCreated { get; set; }
}