// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class Supplier
{
    public long Id { get; set; }

    public string Iban { get; set; }

    public string Bic { get; set; }

    public string VatNr { get; set; }

    public long? LanguageId { get; set; }

    public long? CurrencyId { get; set; }

    public long? AccountingCodeId { get; set; }

    public long? UpfrontPaymentId { get; set; }

    public long? TrackListId { get; set; }

    public string UpfrontIban { get; set; }

    public string UpfrontBic { get; set; }

    public string UpfrontBeneficiaryName { get; set; }

    public string UpfrontBeneficiaryStreet { get; set; }

    public long? UpfrontBeneficiaryCityId { get; set; }

    public string UpfrontBeneficiaryPostalCode { get; set; }

    public bool IsSameIncasso { get; set; }

    public decimal DeliveryPercentage { get; set; }

    public decimal MarginPercentage { get; set; }

    public decimal PurchasePercentage { get; set; }

    public decimal SampleRate { get; set; }

    public long SupplierContactId { get; set; }

    public long AddressId { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public string ContractHeader { get; set; }

    public string SearchName { get; set; }

    public long? ReturnResponsibleId { get; set; }

    public string TemplateSupplierCode { get; set; }

    public bool SearchAllSeasonsOnDocumentImport { get; set; }

    public bool IgnoreInIntrastat { get; set; }

    public string ListPurchaseFormula { get; set; }

    public string WholesaleFormula { get; set; }

    public int ListPurchaseFormulaRoundingPrecision { get; set; }

    public int WholesaleFormulaRoundingPrecision { get; set; }

    public bool PrintRetailPriceOnLabels { get; set; }

    public bool DisableAutoBulk { get; set; }

    public bool HorizontalDivide { get; set; }

    public virtual AccountingCode AccountingCode { get; set; }

    public virtual Address Address { get; set; }

    public virtual ICollection<CollectionDelivery> CollectionDeliveries { get; set; } = new List<CollectionDelivery>();

    public virtual ICollection<Color> Colors { get; set; } = new List<Color>();

    public virtual Currency Currency { get; set; }

    public virtual ICollection<DedicatedSalesRule> DedicatedSalesRules { get; set; } = new List<DedicatedSalesRule>();

    public virtual ICollection<DelayedDeliveryRuleSupplier> DelayedDeliveryRuleSuppliers { get; set; } = new List<DelayedDeliveryRuleSupplier>();

    public virtual ICollection<DeliveryRemarksRule> DeliveryRemarksRules { get; set; } = new List<DeliveryRemarksRule>();

    public virtual ICollection<DiscountRuleSupplier> DiscountRuleSuppliers { get; set; } = new List<DiscountRuleSupplier>();

    public virtual ICollection<DocumentImportConfiguration> DocumentImportConfigurations { get; set; } = new List<DocumentImportConfiguration>();

    public virtual ICollection<DocumentImportMeta> DocumentImportMeta { get; set; } = new List<DocumentImportMeta>();

    public virtual ICollection<ExternalDataImportBatch> ExternalDataImportBatches { get; set; } = new List<ExternalDataImportBatch>();

    public virtual ICollection<FinancialSupervisionByFcRule> FinancialSupervisionByFcRules { get; set; } = new List<FinancialSupervisionByFcRule>();

    public virtual ICollection<FreeTextOnInvoiceRule> FreeTextOnInvoiceRules { get; set; } = new List<FreeTextOnInvoiceRule>();

    public virtual ICollection<InvoiceCompare> InvoiceCompares { get; set; } = new List<InvoiceCompare>();

    public virtual Language Language { get; set; }

    public virtual ICollection<NoDeliveryRuleSupplier> NoDeliveryRuleSuppliers { get; set; } = new List<NoDeliveryRuleSupplier>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual ICollection<RecomaticsInvoice> RecomaticsInvoices { get; set; } = new List<RecomaticsInvoice>();

    public virtual Employee ReturnResponsible { get; set; }

    public virtual ICollection<ReturnRule> ReturnRules { get; set; } = new List<ReturnRule>();

    public virtual ICollection<SalesCondition> SalesConditions { get; set; } = new List<SalesCondition>();

    public virtual ICollection<ShopSupplierCode> ShopSupplierCodes { get; set; } = new List<ShopSupplierCode>();

    public virtual ICollection<SizePack> SizePacks { get; set; } = new List<SizePack>();

    public virtual SupplierContact SupplierContact { get; set; }

    public virtual ICollection<SupplierMarkup> SupplierMarkups { get; set; } = new List<SupplierMarkup>();

    public virtual ICollection<SupplierSalesCondition> SupplierSalesConditions { get; set; } = new List<SupplierSalesCondition>();

    public virtual ICollection<SupplierVat> SupplierVats { get; set; } = new List<SupplierVat>();

    public virtual TrackList TrackList { get; set; }

    public virtual City UpfrontBeneficiaryCity { get; set; }

    public virtual UpfrontPayment UpfrontPayment { get; set; }

    public virtual User UserCreated { get; set; }
}