// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class Target
{
    public long Id { get; set; }

    public DateTime Date { get; set; }

    public decimal SalesTarget { get; set; }

    public decimal SalesResult { get; set; }

    public decimal SalesResultPy { get; set; }

    public int Tickets { get; set; }

    public int Pieces { get; set; }

    public int Visitors { get; set; }

    public long? StockLocationId { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long? ExternalPosId { get; set; }

    public string Comment { get; set; }

    public virtual ExternalPo ExternalPos { get; set; }

    public virtual StockLocation StockLocation { get; set; }

    public virtual User UserCreated { get; set; }
}