// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class TimeframeDifferenceRule
{
    public long Id { get; set; }

    public long ProductLineDeliveryId { get; set; }

    public int SalesTime { get; set; }

    public virtual Rule IdNavigation { get; set; }

    public virtual ProductLineDelivery ProductLineDelivery { get; set; }
}