// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using FCentricProspections.Server.DataModels;
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class User
{
    public long Id { get; set; }

    public string Login { get; set; }

    public bool Blocked { get; set; }

    public virtual ICollection<AccountingCode> AccountingCodes { get; set; } = new List<AccountingCode>();

    public virtual ICollection<AccountingSessionDocument> AccountingSessionDocuments { get; set; } = new List<AccountingSessionDocument>();

    public virtual ICollection<AccountingSessionType> AccountingSessionTypes { get; set; } = new List<AccountingSessionType>();

    public virtual ICollection<AccountingSession> AccountingSessions { get; set; } = new List<AccountingSession>();

    public virtual ICollection<ActionList> ActionLists { get; set; } = new List<ActionList>();

    public virtual ICollection<Action> Actions { get; set; } = new List<Action>();

    public virtual ICollection<Address> Addresses { get; set; } = new List<Address>();

    public virtual ICollection<AdvancedPaymentState> AdvancedPaymentStates { get; set; } = new List<AdvancedPaymentState>();

    public virtual ICollection<AdvancedPayment> AdvancedPayments { get; set; } = new List<AdvancedPayment>();

    public virtual ICollection<AgeCategory> AgeCategories { get; set; } = new List<AgeCategory>();

    public virtual ICollection<AgentContact> AgentContacts { get; set; } = new List<AgentContact>();

    public virtual ICollection<AgentProductLineDelivery> AgentProductLineDeliveries { get; set; } = new List<AgentProductLineDelivery>();

    public virtual ICollection<AgentRegion> AgentRegions { get; set; } = new List<AgentRegion>();

    public virtual ICollection<Agent> Agents { get; set; } = new List<Agent>();

    public virtual ICollection<AppointmentCaresponsible> AppointmentCaresponsibles { get; set; } = new List<AppointmentCaresponsible>();

    public virtual ICollection<AppointmentContact> AppointmentContacts { get; set; } = new List<AppointmentContact>();

    public virtual ICollection<AppointmentDepartmentResponsible> AppointmentDepartmentResponsibles { get; set; } = new List<AppointmentDepartmentResponsible>();

    public virtual ICollection<AppointmentSalesResponsible> AppointmentSalesResponsibles { get; set; } = new List<AppointmentSalesResponsible>();

    public virtual ICollection<AppointmentState> AppointmentStates { get; set; } = new List<AppointmentState>();

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual ICollection<AvailabilityDay> AvailabilityDays { get; set; } = new List<AvailabilityDay>();

    public virtual ICollection<AvailabilityType> AvailabilityTypes { get; set; } = new List<AvailabilityType>();

    public virtual ICollection<Barcode> Barcodes { get; set; } = new List<Barcode>();

    public virtual ICollection<BleckmannImportedFile> BleckmannImportedFiles { get; set; } = new List<BleckmannImportedFile>();

    public virtual ICollection<BleckmannSkuSync> BleckmannSkuSyncs { get; set; } = new List<BleckmannSkuSync>();

    public virtual ICollection<BleckmannTransportState> BleckmannTransportStates { get; set; } = new List<BleckmannTransportState>();

    public virtual ICollection<BlockedByFdiReason> BlockedByFdiReasons { get; set; } = new List<BlockedByFdiReason>();

    public virtual ICollection<BlockedType> BlockedTypes { get; set; } = new List<BlockedType>();

    public virtual ICollection<Brand> Brands { get; set; } = new List<Brand>();

    public virtual ICollection<City> Cities { get; set; } = new List<City>();

    public virtual ICollection<CityPriceRegion> CityPriceRegions { get; set; } = new List<CityPriceRegion>();

    public virtual ICollection<CollectionDelivery> CollectionDeliveries { get; set; } = new List<CollectionDelivery>();

    public virtual ICollection<CollectionDeliveryCategory> CollectionDeliveryCategories { get; set; } = new List<CollectionDeliveryCategory>();

    public virtual ICollection<CollectionDeliveryLocation> CollectionDeliveryLocations { get; set; } = new List<CollectionDeliveryLocation>();

    public virtual ICollection<CollectionDeliveryType> CollectionDeliveryTypes { get; set; } = new List<CollectionDeliveryType>();

    public virtual ICollection<CollectionDeliveryWarehouse> CollectionDeliveryWarehouses { get; set; } = new List<CollectionDeliveryWarehouse>();

    public virtual ICollection<CollectionSaleInvitationSendRange> CollectionSaleInvitationSendRanges { get; set; } = new List<CollectionSaleInvitationSendRange>();

    public virtual ICollection<CollectionSaleSignUp> CollectionSaleSignUps { get; set; } = new List<CollectionSaleSignUp>();

    public virtual ICollection<CollectionSalesInvitationType> CollectionSalesInvitationTypes { get; set; } = new List<CollectionSalesInvitationType>();

    public virtual ICollection<Color> Colors { get; set; } = new List<Color>();

    public virtual ICollection<CommercialLocation> CommercialLocations { get; set; } = new List<CommercialLocation>();

    public virtual ICollection<Company> Companies { get; set; } = new List<Company>();

    public virtual ICollection<CompetitorBrand> CompetitorBrands { get; set; } = new List<CompetitorBrand>();

    public virtual ICollection<ContactChannelDescription> ContactChannelDescriptions { get; set; } = new List<ContactChannelDescription>();

    public virtual ICollection<ContactChannelInterestType> ContactChannelInterestTypes { get; set; } = new List<ContactChannelInterestType>();

    public virtual ICollection<ContactChannelInterest> ContactChannelInterests { get; set; } = new List<ContactChannelInterest>();

    public virtual ICollection<ContactChannelOptIn> ContactChannelOptIns { get; set; } = new List<ContactChannelOptIn>();

    public virtual ICollection<ContactChannelType> ContactChannelTypes { get; set; } = new List<ContactChannelType>();

    public virtual ICollection<ContactChannel> ContactChannels { get; set; } = new List<ContactChannel>();

    public virtual ICollection<ContactType> ContactTypes { get; set; } = new List<ContactType>();

    public virtual ICollection<Contact> Contacts { get; set; } = new List<Contact>();

    public virtual ICollection<ContractState> ContractStates { get; set; } = new List<ContractState>();

    public virtual ICollection<Country> Countries { get; set; } = new List<Country>();

    public virtual ICollection<Currency> Currencies { get; set; } = new List<Currency>();

    public virtual ICollection<CustomerCode> CustomerCodes { get; set; } = new List<CustomerCode>();

    public virtual ICollection<CustomerContact> CustomerContacts { get; set; } = new List<CustomerContact>();

    public virtual ICollection<CustomerGuarantee> CustomerGuarantees { get; set; } = new List<CustomerGuarantee>();

    public virtual ICollection<CustomerInvitation> CustomerInvitations { get; set; } = new List<CustomerInvitation>();

    public virtual ICollection<CustomerLegalHistory> CustomerLegalHistories { get; set; } = new List<CustomerLegalHistory>();

    public virtual ICollection<CustomerLoyalty> CustomerLoyalties { get; set; } = new List<CustomerLoyalty>();

    public virtual ICollection<CustomerOptIn> CustomerOptIns { get; set; } = new List<CustomerOptIn>();

    public virtual ICollection<CustomerReportConfiguration> CustomerReportConfigurations { get; set; } = new List<CustomerReportConfiguration>();

    public virtual ICollection<CustomerRule> CustomerRules { get; set; } = new List<CustomerRule>();

    public virtual ICollection<CustomerShop> CustomerShops { get; set; } = new List<CustomerShop>();

    public virtual ICollection<CustomerTypeFeature> CustomerTypeFeatures { get; set; } = new List<CustomerTypeFeature>();

    public virtual ICollection<CustomerType> CustomerTypes { get; set; } = new List<CustomerType>();

    public virtual ICollection<CustomerWifiCode> CustomerWifiCodes { get; set; } = new List<CustomerWifiCode>();

    public virtual ICollection<CustomerWpsStatus> CustomerWpsStatuses { get; set; } = new List<CustomerWpsStatus>();

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual ICollection<DataQueryLog> DataQueryLogs { get; set; } = new List<DataQueryLog>();

    public virtual ICollection<DelayedDeliveryProposedRuleShop> DelayedDeliveryProposedRuleShops { get; set; } = new List<DelayedDeliveryProposedRuleShop>();

    public virtual ICollection<DelayedDeliveryRuleProductLineDelivery> DelayedDeliveryRuleProductLineDeliveries { get; set; } = new List<DelayedDeliveryRuleProductLineDelivery>();

    public virtual ICollection<DelayedDeliveryRuleShop> DelayedDeliveryRuleShops { get; set; } = new List<DelayedDeliveryRuleShop>();

    public virtual ICollection<DelayedDeliveryRuleSupplier> DelayedDeliveryRuleSuppliers { get; set; } = new List<DelayedDeliveryRuleSupplier>();

    public virtual ICollection<DeliveryLocationType> DeliveryLocationTypes { get; set; } = new List<DeliveryLocationType>();

    public virtual ICollection<DeliveryMethod> DeliveryMethods { get; set; } = new List<DeliveryMethod>();

    public virtual ICollection<DeliveryRemarksRuleProductLineDelivery> DeliveryRemarksRuleProductLineDeliveries { get; set; } = new List<DeliveryRemarksRuleProductLineDelivery>();

    public virtual ICollection<DeliveryRemarksRuleShop> DeliveryRemarksRuleShops { get; set; } = new List<DeliveryRemarksRuleShop>();

    public virtual ICollection<DeliveryWindow> DeliveryWindows { get; set; } = new List<DeliveryWindow>();

    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();

    public virtual ICollection<DiscountCampaignLineDetail> DiscountCampaignLineDetails { get; set; } = new List<DiscountCampaignLineDetail>();

    public virtual ICollection<DiscountCampaignLine> DiscountCampaignLines { get; set; } = new List<DiscountCampaignLine>();

    public virtual ICollection<DiscountCampaign> DiscountCampaigns { get; set; } = new List<DiscountCampaign>();

    public virtual ICollection<DiscountRuleSupplier> DiscountRuleSuppliers { get; set; } = new List<DiscountRuleSupplier>();

    public virtual ICollection<DocumentBleckmannTransportState> DocumentBleckmannTransportStates { get; set; } = new List<DocumentBleckmannTransportState>();

    public virtual ICollection<DocumentDeliveryState> DocumentDeliveryStates { get; set; } = new List<DocumentDeliveryState>();

    public virtual ICollection<DocumentFlow> DocumentFlows { get; set; } = new List<DocumentFlow>();

    public virtual ICollection<DocumentImportConfigurationMapping> DocumentImportConfigurationMappings { get; set; } = new List<DocumentImportConfigurationMapping>();

    public virtual ICollection<DocumentImportConfiguration> DocumentImportConfigurations { get; set; } = new List<DocumentImportConfiguration>();

    public virtual ICollection<DocumentImportMeta> DocumentImportMeta { get; set; } = new List<DocumentImportMeta>();

    public virtual ICollection<DocumentImportMetaError> DocumentImportMetaErrors { get; set; } = new List<DocumentImportMetaError>();

    public virtual ICollection<DocumentImportMetaStatus> DocumentImportMetaStatuses { get; set; } = new List<DocumentImportMetaStatus>();

    public virtual ICollection<DocumentImportMetaWarning> DocumentImportMetaWarnings { get; set; } = new List<DocumentImportMetaWarning>();

    public virtual ICollection<DocumentLineDetail> DocumentLineDetails { get; set; } = new List<DocumentLineDetail>();

    public virtual ICollection<DocumentLine> DocumentLines { get; set; } = new List<DocumentLine>();

    public virtual ICollection<DocumentPaymentType> DocumentPaymentTypes { get; set; } = new List<DocumentPaymentType>();

    public virtual ICollection<DocumentPayment> DocumentPayments { get; set; } = new List<DocumentPayment>();

    public virtual ICollection<DocumentRelation> DocumentRelations { get; set; } = new List<DocumentRelation>();

    public virtual ICollection<DocumentRule> DocumentRules { get; set; } = new List<DocumentRule>();

    public virtual ICollection<DocumentSnapshot> DocumentSnapshots { get; set; } = new List<DocumentSnapshot>();

    public virtual ICollection<DocumentState> DocumentStates { get; set; } = new List<DocumentState>();

    public virtual ICollection<DocumentTransfer> DocumentTransfers { get; set; } = new List<DocumentTransfer>();

    public virtual ICollection<DocumentType> DocumentTypes { get; set; } = new List<DocumentType>();

    public virtual ICollection<Document> Documents { get; set; } = new List<Document>();

    public virtual ICollection<EmailTemplatePlaceholder> EmailTemplatePlaceholders { get; set; } = new List<EmailTemplatePlaceholder>();

    public virtual ICollection<EmailTemplate> EmailTemplates { get; set; } = new List<EmailTemplate>();

    public virtual ICollection<Employee> EmployeeUserCreateds { get; set; } = new List<Employee>();

    public virtual ICollection<Employee> EmployeeUsers { get; set; } = new List<Employee>();

    public virtual ICollection<ExpenseOpiPrintRequest> ExpenseOpiPrintRequests { get; set; } = new List<ExpenseOpiPrintRequest>();

    public virtual ICollection<ExpenseType> ExpenseTypes { get; set; } = new List<ExpenseType>();

    public virtual ICollection<Expense> Expenses { get; set; } = new List<Expense>();

    public virtual ICollection<ExternalDataImportBatchLog> ExternalDataImportBatchLogs { get; set; } = new List<ExternalDataImportBatchLog>();

    public virtual ICollection<ExternalDataImportBatchSchedule> ExternalDataImportBatchSchedules { get; set; } = new List<ExternalDataImportBatchSchedule>();

    public virtual ICollection<ExternalDataImportBatchStatus> ExternalDataImportBatchStatuses { get; set; } = new List<ExternalDataImportBatchStatus>();

    public virtual ICollection<ExternalDataImportBatch> ExternalDataImportBatches { get; set; } = new List<ExternalDataImportBatch>();

    public virtual ICollection<ExternalDataImportType> ExternalDataImportTypes { get; set; } = new List<ExternalDataImportType>();

    public virtual ICollection<ExternalPo> ExternalPos { get; set; } = new List<ExternalPo>();

    public virtual ICollection<ExternalPosJournalEntry> ExternalPosJournalEntries { get; set; } = new List<ExternalPosJournalEntry>();

    public virtual ICollection<ExternalPosJournalEntryType> ExternalPosJournalEntryTypes { get; set; } = new List<ExternalPosJournalEntryType>();

    public virtual ICollection<ExternalPosJournalExpense> ExternalPosJournalExpenses { get; set; } = new List<ExternalPosJournalExpense>();

    public virtual ICollection<ExternalPosJournalInvoice> ExternalPosJournalInvoices { get; set; } = new List<ExternalPosJournalInvoice>();

    public virtual ICollection<ExternalPosJournalVoucher> ExternalPosJournalVouchers { get; set; } = new List<ExternalPosJournalVoucher>();

    public virtual ICollection<ExternalPosJournal> ExternalPosJournals { get; set; } = new List<ExternalPosJournal>();

    public virtual ICollection<ExternalSalesPlatformFashionProductColor> ExternalSalesPlatformFashionProductColors { get; set; } = new List<ExternalSalesPlatformFashionProductColor>();

    public virtual ICollection<ExternalSalesPlatformStockSyncLog> ExternalSalesPlatformStockSyncLogs { get; set; } = new List<ExternalSalesPlatformStockSyncLog>();

    public virtual ICollection<ExternalSalesPlatform> ExternalSalesPlatforms { get; set; } = new List<ExternalSalesPlatform>();

    public virtual ICollection<FashionDocumentPicture> FashionDocumentPictures { get; set; } = new List<FashionDocumentPicture>();

    public virtual ICollection<FashionDocumentShop> FashionDocumentShops { get; set; } = new List<FashionDocumentShop>();

    public virtual ICollection<FashionProductColor> FashionProductColors { get; set; } = new List<FashionProductColor>();

    public virtual ICollection<FashionProductPicture> FashionProductPictures { get; set; } = new List<FashionProductPicture>();

    public virtual ICollection<FashionProductSizePack> FashionProductSizePacks { get; set; } = new List<FashionProductSizePack>();

    public virtual ICollection<FashionProductSizeRegion> FashionProductSizeRegions { get; set; } = new List<FashionProductSizeRegion>();

    public virtual ICollection<FashionProductSize> FashionProductSizes { get; set; } = new List<FashionProductSize>();

    public virtual ICollection<FdiExportSessionDocument> FdiExportSessionDocuments { get; set; } = new List<FdiExportSessionDocument>();

    public virtual ICollection<FdiExportSession> FdiExportSessions { get; set; } = new List<FdiExportSession>();

    public virtual ICollection<FileImportLogErrorType> FileImportLogErrorTypes { get; set; } = new List<FileImportLogErrorType>();

    public virtual ICollection<FileImportLogError> FileImportLogErrors { get; set; } = new List<FileImportLogError>();

    public virtual ICollection<FileImportLogType> FileImportLogTypes { get; set; } = new List<FileImportLogType>();

    public virtual ICollection<FileImportLog> FileImportLogs { get; set; } = new List<FileImportLog>();

    public virtual ICollection<FinancialSupervisionByFcRuleProductLineDelivery> FinancialSupervisionByFcRuleProductLineDeliveries { get; set; } = new List<FinancialSupervisionByFcRuleProductLineDelivery>();

    public virtual ICollection<FinancialSupervisionByFcRuleShop> FinancialSupervisionByFcRuleShops { get; set; } = new List<FinancialSupervisionByFcRuleShop>();

    public virtual ICollection<FreeTextOnInvoiceRuleProductLineDelivery> FreeTextOnInvoiceRuleProductLineDeliveries { get; set; } = new List<FreeTextOnInvoiceRuleProductLineDelivery>();

    public virtual ICollection<FreeTextOnInvoiceRuleShop> FreeTextOnInvoiceRuleShops { get; set; } = new List<FreeTextOnInvoiceRuleShop>();

    public virtual ICollection<Gender> Genders { get; set; } = new List<Gender>();

    public virtual ICollection<GridConfigurationGroup> GridConfigurationGroups { get; set; } = new List<GridConfigurationGroup>();

    public virtual ICollection<GridConfiguration> GridConfigurations { get; set; } = new List<GridConfiguration>();

    public virtual ICollection<History> Histories { get; set; } = new List<History>();

    public virtual ICollection<IntraMirrorConfig> IntraMirrorConfigs { get; set; } = new List<IntraMirrorConfig>();

    public virtual ICollection<IntraMirrorProductLineDelivery> IntraMirrorProductLineDeliveries { get; set; } = new List<IntraMirrorProductLineDelivery>();

    public virtual ICollection<InvitationType> InvitationTypes { get; set; } = new List<InvitationType>();

    public virtual ICollection<Invitation> Invitations { get; set; } = new List<Invitation>();

    public virtual ICollection<InvoiceCompare> InvoiceCompares { get; set; } = new List<InvoiceCompare>();

    public virtual ICollection<KlaviyoCollectionSaleCustomerSync> KlaviyoCollectionSaleCustomerSyncs { get; set; } = new List<KlaviyoCollectionSaleCustomerSync>();

    public virtual ICollection<KlaviyoDocumentSync> KlaviyoDocumentSyncs { get; set; } = new List<KlaviyoDocumentSync>();

    public virtual ICollection<KlaviyoRetailDocumentSync> KlaviyoRetailDocumentSyncs { get; set; } = new List<KlaviyoRetailDocumentSync>();

    public virtual ICollection<KlaviyoShopSync> KlaviyoShopSyncs { get; set; } = new List<KlaviyoShopSync>();

    public virtual ICollection<LabelPrintJob> LabelPrintJobs { get; set; } = new List<LabelPrintJob>();

    public virtual ICollection<LabelPrinter> LabelPrinters { get; set; } = new List<LabelPrinter>();

    public virtual ICollection<Language> Languages { get; set; } = new List<Language>();

    public virtual ICollection<LegalForm> LegalForms { get; set; } = new List<LegalForm>();

    public virtual ICollection<Line> Lines { get; set; } = new List<Line>();

    public virtual ICollection<LoyaltyType> LoyaltyTypes { get; set; } = new List<LoyaltyType>();

    public virtual ICollection<MailLog> MailLogs { get; set; } = new List<MailLog>();

    public virtual ICollection<ManualDocumentTransfer> ManualDocumentTransfers { get; set; } = new List<ManualDocumentTransfer>();

    public virtual ICollection<MobileDeviceLogin> MobileDeviceLogins { get; set; } = new List<MobileDeviceLogin>();

    public virtual ICollection<ModificationType> ModificationTypes { get; set; } = new List<ModificationType>();

    public virtual ICollection<NoDeliveryRuleSupplier> NoDeliveryRuleSuppliers { get; set; } = new List<NoDeliveryRuleSupplier>();

    public virtual ICollection<NosCoType> NosCoTypes { get; set; } = new List<NosCoType>();

    public virtual ICollection<OptInSource> OptInSources { get; set; } = new List<OptInSource>();

    public virtual ICollection<OptInType> OptInTypes { get; set; } = new List<OptInType>();

    public virtual ICollection<PaymentCondition> PaymentConditions { get; set; } = new List<PaymentCondition>();

    public virtual ICollection<Picture> Pictures { get; set; } = new List<Picture>();

    public virtual ICollection<Po> Pos { get; set; } = new List<Po>();

    public virtual ICollection<PosAccountingSessionEntry> PosAccountingSessionEntries { get; set; } = new List<PosAccountingSessionEntry>();

    public virtual ICollection<PosAccountingSession> PosAccountingSessions { get; set; } = new List<PosAccountingSession>();

    public virtual ICollection<PosDiscountReason> PosDiscountReasons { get; set; } = new List<PosDiscountReason>();

    public virtual ICollection<PosEjournal> PosEjournals { get; set; } = new List<PosEjournal>();

    public virtual ICollection<PosOptIn> PosOptIns { get; set; } = new List<PosOptIn>();

    public virtual ICollection<PosSession> PosSessions { get; set; } = new List<PosSession>();

    public virtual ICollection<PosTicketCancellationReason> PosTicketCancellationReasons { get; set; } = new List<PosTicketCancellationReason>();

    public virtual ICollection<ProductAlias> ProductAliases { get; set; } = new List<ProductAlias>();

    public virtual ICollection<ProductCategory> ProductCategories { get; set; } = new List<ProductCategory>();

    public virtual ICollection<ProductCategoryAlias> ProductCategoryAliases { get; set; } = new List<ProductCategoryAlias>();

    public virtual ICollection<ProductDeliveryWindow> ProductDeliveryWindows { get; set; } = new List<ProductDeliveryWindow>();

    public virtual ICollection<ProductGroup> ProductGroups { get; set; } = new List<ProductGroup>();

    public virtual ICollection<ProductLineDelivery> ProductLineDeliveries { get; set; } = new List<ProductLineDelivery>();

    public virtual ICollection<ProductLine> ProductLines { get; set; } = new List<ProductLine>();

    public virtual ICollection<ProductMatrix> ProductMatrices { get; set; } = new List<ProductMatrix>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual ICollection<Prospection> Prospections { get; set; } = new List<Prospection>();

    public virtual ICollection<Province> Provinces { get; set; } = new List<Province>();

    public virtual ICollection<PublicHoliday> PublicHolidays { get; set; } = new List<PublicHoliday>();

    public virtual ICollection<PublicationCountry> PublicationCountries { get; set; } = new List<PublicationCountry>();

    public virtual ICollection<Publication> Publications { get; set; } = new List<Publication>();

    public virtual ICollection<RatingType> RatingTypes { get; set; } = new List<RatingType>();

    public virtual ICollection<RecomaticsInvoiceCollectionDelivery> RecomaticsInvoiceCollectionDeliveries { get; set; } = new List<RecomaticsInvoiceCollectionDelivery>();

    public virtual ICollection<RecomaticsInvoiceFileImportLog> RecomaticsInvoiceFileImportLogs { get; set; } = new List<RecomaticsInvoiceFileImportLog>();

    public virtual ICollection<RecomaticsInvoice> RecomaticsInvoices { get; set; } = new List<RecomaticsInvoice>();

    public virtual ICollection<RecurringAppointment> RecurringAppointments { get; set; } = new List<RecurringAppointment>();

    public virtual ICollection<Region> Regions { get; set; } = new List<Region>();

    public virtual ICollection<ReportDefinition> ReportDefinitions { get; set; } = new List<ReportDefinition>();

    public virtual ICollection<ReturnApprovedState> ReturnApprovedStates { get; set; } = new List<ReturnApprovedState>();

    public virtual ICollection<ReturnDestination> ReturnDestinations { get; set; } = new List<ReturnDestination>();

    public virtual ICollection<ReturnReason> ReturnReasons { get; set; } = new List<ReturnReason>();

    public virtual ICollection<ReturnStateAction> ReturnStateActions { get; set; } = new List<ReturnStateAction>();

    public virtual ICollection<ReturnState> ReturnStates { get; set; } = new List<ReturnState>();

    public virtual ICollection<ReturnSupplierAction> ReturnSupplierActions { get; set; } = new List<ReturnSupplierAction>();

    public virtual ICollection<ReturnTracking> ReturnTrackings { get; set; } = new List<ReturnTracking>();

    public virtual ICollection<RoadAppointmentProductLine> RoadAppointmentProductLines { get; set; } = new List<RoadAppointmentProductLine>();

    public virtual ICollection<Rule> Rules { get; set; } = new List<Rule>();

    public virtual ICollection<SalesConditionDiscountExcludedProduct> SalesConditionDiscountExcludedProducts { get; set; } = new List<SalesConditionDiscountExcludedProduct>();

    public virtual ICollection<SalesConditionDiscount> SalesConditionDiscounts { get; set; } = new List<SalesConditionDiscount>();

    public virtual ICollection<SalesConditionEmployee> SalesConditionEmployees { get; set; } = new List<SalesConditionEmployee>();

    public virtual ICollection<SalesConditionGroup> SalesConditionGroups { get; set; } = new List<SalesConditionGroup>();

    public virtual ICollection<SalesConditionPeriod> SalesConditionPeriods { get; set; } = new List<SalesConditionPeriod>();

    public virtual ICollection<SalesConditionPlanning> SalesConditionPlannings { get; set; } = new List<SalesConditionPlanning>();

    public virtual ICollection<SalesConditionShowroom> SalesConditionShowrooms { get; set; } = new List<SalesConditionShowroom>();

    public virtual ICollection<SalesConditionType> SalesConditionTypes { get; set; } = new List<SalesConditionType>();

    public virtual ICollection<SalesCondition> SalesConditions { get; set; } = new List<SalesCondition>();

    public virtual ICollection<SalesPeriodCurrencyCourse> SalesPeriodCurrencyCourses { get; set; } = new List<SalesPeriodCurrencyCourse>();

    public virtual ICollection<SalesPeriodType> SalesPeriodTypes { get; set; } = new List<SalesPeriodType>();

    public virtual ICollection<SalesPeriod> SalesPeriods { get; set; } = new List<SalesPeriod>();

    public virtual ICollection<SampleDestination> SampleDestinations { get; set; } = new List<SampleDestination>();

    public virtual ICollection<SegmentType> SegmentTypes { get; set; } = new List<SegmentType>();

    public virtual ICollection<ShopAgeCategory> ShopAgeCategories { get; set; } = new List<ShopAgeCategory>();

    public virtual ICollection<ShopCommercialLocation> ShopCommercialLocations { get; set; } = new List<ShopCommercialLocation>();

    public virtual ICollection<ShopCompetitorBrand> ShopCompetitorBrands { get; set; } = new List<ShopCompetitorBrand>();

    public virtual ICollection<ShopCompetitorProductLine> ShopCompetitorProductLines { get; set; } = new List<ShopCompetitorProductLine>();

    public virtual ICollection<ShopContact> ShopContacts { get; set; } = new List<ShopContact>();

    public virtual ICollection<ShopDelivery> ShopDeliveries { get; set; } = new List<ShopDelivery>();

    public virtual ICollection<ShopDeliveryOrigin> ShopDeliveryOrigins { get; set; } = new List<ShopDeliveryOrigin>();

    public virtual ICollection<ShopDeliveryState> ShopDeliveryStates { get; set; } = new List<ShopDeliveryState>();

    public virtual ICollection<ShopDeliveryType> ShopDeliveryTypes { get; set; } = new List<ShopDeliveryType>();

    public virtual ICollection<ShopGender> ShopGenders { get; set; } = new List<ShopGender>();

    public virtual ICollection<ShopLine> ShopLines { get; set; } = new List<ShopLine>();

    public virtual ICollection<ShopPicture> ShopPictures { get; set; } = new List<ShopPicture>();

    public virtual ICollection<ShopSegmentType> ShopSegmentTypes { get; set; } = new List<ShopSegmentType>();

    public virtual ICollection<ShopSupplierCode> ShopSupplierCodes { get; set; } = new List<ShopSupplierCode>();

    public virtual ICollection<ShopType> ShopTypes { get; set; } = new List<ShopType>();

    public virtual ICollection<ShopVisit> ShopVisits { get; set; } = new List<ShopVisit>();

    public virtual ICollection<ShopifyFashionProductColor> ShopifyFashionProductColors { get; set; } = new List<ShopifyFashionProductColor>();

    public virtual ICollection<ShopifyProcessedOrder> ShopifyProcessedOrders { get; set; } = new List<ShopifyProcessedOrder>();

    public virtual ICollection<Shop> Shops { get; set; } = new List<Shop>();

    public virtual ICollection<ShowroomAppointmentSalesConditionReason> ShowroomAppointmentSalesConditionReasons { get; set; } = new List<ShowroomAppointmentSalesConditionReason>();

    public virtual ICollection<ShowroomAppointmentSalesConditionResponse> ShowroomAppointmentSalesConditionResponses { get; set; } = new List<ShowroomAppointmentSalesConditionResponse>();

    public virtual ICollection<ShowroomAppointmentSalesConditionSellOut> ShowroomAppointmentSalesConditionSellOuts { get; set; } = new List<ShowroomAppointmentSalesConditionSellOut>();

    public virtual ICollection<ShowroomAppointmentSalesConditionShopAction> ShowroomAppointmentSalesConditionShopActions { get; set; } = new List<ShowroomAppointmentSalesConditionShopAction>();

    public virtual ICollection<ShowroomAppointmentSalesConditionShop> ShowroomAppointmentSalesConditionShops { get; set; } = new List<ShowroomAppointmentSalesConditionShop>();

    public virtual ICollection<ShowroomAppointmentSalesConditionSigning> ShowroomAppointmentSalesConditionSignings { get; set; } = new List<ShowroomAppointmentSalesConditionSigning>();

    public virtual ICollection<ShowroomAppointmentSalesConditionUnsignedReason> ShowroomAppointmentSalesConditionUnsignedReasons { get; set; } = new List<ShowroomAppointmentSalesConditionUnsignedReason>();

    public virtual ICollection<ShowroomAppointmentSalesCondition> ShowroomAppointmentSalesConditions { get; set; } = new List<ShowroomAppointmentSalesCondition>();

    public virtual ICollection<Showroom> Showrooms { get; set; } = new List<Showroom>();

    public virtual ICollection<SizePackQuantity> SizePackQuantities { get; set; } = new List<SizePackQuantity>();

    public virtual ICollection<SizePack> SizePacks { get; set; } = new List<SizePack>();

    public virtual ICollection<SizeScale> SizeScales { get; set; } = new List<SizeScale>();

    public virtual ICollection<SizeType> SizeTypes { get; set; } = new List<SizeType>();

    public virtual ICollection<Size> Sizes { get; set; } = new List<Size>();

    public virtual ICollection<Spanco> Spancos { get; set; } = new List<Spanco>();

    public virtual ICollection<StockLocation> StockLocations { get; set; } = new List<StockLocation>();

    public virtual ICollection<SupplierContact> SupplierContacts { get; set; } = new List<SupplierContact>();

    public virtual ICollection<SupplierMarkup> SupplierMarkups { get; set; } = new List<SupplierMarkup>();

    public virtual ICollection<SupplierSalesCondition> SupplierSalesConditions { get; set; } = new List<SupplierSalesCondition>();

    public virtual ICollection<SupplierVat> SupplierVats { get; set; } = new List<SupplierVat>();

    public virtual ICollection<Supplier> Suppliers { get; set; } = new List<Supplier>();

    public virtual ICollection<Target> Targets { get; set; } = new List<Target>();

    public virtual ICollection<ToDoStatus> ToDoStatuses { get; set; } = new List<ToDoStatus>();

    public virtual ICollection<ToDo> ToDos { get; set; } = new List<ToDo>();

    public virtual ICollection<TrackList> TrackLists { get; set; } = new List<TrackList>();

    public virtual ICollection<TransportType> TransportTypes { get; set; } = new List<TransportType>();

    public virtual ICollection<UpfrontPayment> UpfrontPayments { get; set; } = new List<UpfrontPayment>();

    public virtual ICollection<VatType> VatTypes { get; set; } = new List<VatType>();

    public virtual ICollection<Vat> Vats { get; set; } = new List<Vat>();

    public virtual ICollection<VoucherOverruleReason> VoucherOverruleReasons { get; set; } = new List<VoucherOverruleReason>();

    public virtual ICollection<VoucherType> VoucherTypes { get; set; } = new List<VoucherType>();

    public virtual ICollection<Voucher> Vouchers { get; set; } = new List<Voucher>();

    public virtual ICollection<Weather> Weathers { get; set; } = new List<Weather>();

    public virtual ICollection<WifiCode> WifiCodes { get; set; } = new List<WifiCode>();

    public virtual ICollection<WpsPrePayment> WpsPrePayments { get; set; } = new List<WpsPrePayment>();

    public virtual ICollection<ExternalPo> ExternalPosNavigation { get; set; } = new List<ExternalPo>();

    public virtual ICollection<ExternalSalesPlatform> ExternalSalesPlatformsNavigation { get; set; } = new List<ExternalSalesPlatform>();

    public virtual ICollection<Role> Roles { get; set; } = new List<Role>();
}