// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using FCentricProspections.Server.DataModels;
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class User
{
    public long Id { get; set; }

    public string Login { get; set; }

    public bool Blocked { get; set; }

    public virtual ICollection<Address> Addresses { get; set; } = new List<Address>();

    public virtual ICollection<AppointmentState> AppointmentStates { get; set; } = new List<AppointmentState>();

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual ICollection<Brand> Brands { get; set; } = new List<Brand>();

    public virtual ICollection<City> Cities { get; set; } = new List<City>();

    public virtual ICollection<CompetitorBrand> CompetitorBrands { get; set; } = new List<CompetitorBrand>();

    public virtual ICollection<Contact> Contacts { get; set; } = new List<Contact>();

    public virtual ICollection<Country> Countries { get; set; } = new List<Country>();

    public virtual ICollection<CustomerShop> CustomerShops { get; set; } = new List<CustomerShop>();

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual ICollection<Employee> EmployeeUserCreateds { get; set; } = new List<Employee>();

    public virtual ICollection<ProductLineDelivery> ProductLineDeliveries { get; set; } = new List<ProductLineDelivery>();

    public virtual ICollection<ProductLine> ProductLines { get; set; } = new List<ProductLine>();

    public virtual ICollection<Prospection> Prospections { get; set; } = new List<Prospection>();

    public virtual ICollection<SalesPeriod> SalesPeriods { get; set; } = new List<SalesPeriod>();

    public virtual ICollection<ShopDelivery> ShopDeliveries { get; set; } = new List<ShopDelivery>();

    public virtual ICollection<Shop> Shops { get; set; } = new List<Shop>();

    public virtual ICollection<ToDoStatus> ToDoStatuses { get; set; } = new List<ToDoStatus>();

    public virtual ICollection<ToDoType> ToDoTypes { get; set; } = new List<ToDoType>();

    public virtual ICollection<ToDo> ToDos { get; set; } = new List<ToDo>();
}