// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class Vat
{
    public long Id { get; set; }

    public string Code { get; set; }

    public decimal Rate { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long VatTypeId { get; set; }

    public virtual ICollection<DocumentLineDetail> DocumentLineDetails { get; set; } = new List<DocumentLineDetail>();

    public virtual ICollection<FashionProductSizeRegion> FashionProductSizeRegions { get; set; } = new List<FashionProductSizeRegion>();

    public virtual ICollection<FashionProductSize> FashionProductSizes { get; set; } = new List<FashionProductSize>();

    public virtual ICollection<SupplierVat> SupplierVats { get; set; } = new List<SupplierVat>();

    public virtual User UserCreated { get; set; }

    public virtual VatType VatType { get; set; }
}