// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class VatType
{
    public long Id { get; set; }

    public string Code { get; set; }

    public bool IsTaxLevy { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual ICollection<Country> Countries { get; set; } = new List<Country>();

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual ICollection<Document> Documents { get; set; } = new List<Document>();

    public virtual User UserCreated { get; set; }

    public virtual ICollection<Vat> Vats { get; set; } = new List<Vat>();
}