// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class Voucher
{
    public long Id { get; set; }

    public long VoucherTypeId { get; set; }

    public decimal Amount { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public DateTime? ExpireDate { get; set; }

    public long? VoucherOverruleReasonId { get; set; }

    public DateTime? VoucherOverruleDate { get; set; }

    public string OverruleRemark { get; set; }

    public DateTime? TransferedToShopifyDate { get; set; }

    public virtual ICollection<DocumentPayment> DocumentPayments { get; set; } = new List<DocumentPayment>();

    public virtual User UserCreated { get; set; }

    public virtual ICollection<VoucherBarcode> VoucherBarcodes { get; set; } = new List<VoucherBarcode>();

    public virtual VoucherOverruleReason VoucherOverruleReason { get; set; }

    public virtual VoucherType VoucherType { get; set; }
}