// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class VoucherBarcode
{
    public long Id { get; set; }

    public long VoucherId { get; set; }

    public virtual ICollection<FashionDocument> FashionDocuments { get; set; } = new List<FashionDocument>();

    public virtual Barcode IdNavigation { get; set; }

    public virtual Voucher Voucher { get; set; }
}