// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class Weather
{
    public long Id { get; set; }

    public DateTime Date { get; set; }

    public decimal CloudCover { get; set; }

    public decimal Humidity { get; set; }

    public decimal Precipitation { get; set; }

    public decimal TempMin { get; set; }

    public decimal TempMax { get; set; }

    public decimal TempAfternoon { get; set; }

    public decimal TempNight { get; set; }

    public decimal TempEvening { get; set; }

    public decimal TempMorning { get; set; }

    public decimal Pressure { get; set; }

    public decimal WindSpeed { get; set; }

    public decimal WindDirection { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual User UserCreated { get; set; }
}