// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class WebPlatformClient
{
    public long Id { get; set; }

    public string Name { get; set; }

    public string Issuer { get; set; }

    public string BasicAuthorizationToken { get; set; }

    public string SigningToken { get; set; }

    public long WebPlatformDomainId { get; set; }

    public virtual ICollection<WebPlatformClientContact> WebPlatformClientContacts { get; set; } = new List<WebPlatformClientContact>();

    public virtual WebPlatformDomain WebPlatformDomain { get; set; }
}