// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class WebPlatformClientContact
{
    public long Id { get; set; }

    public long WebPlatformClientId { get; set; }

    public long WebPlatformContactId { get; set; }

    public virtual WebPlatformClient WebPlatformClient { get; set; }
}