// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class WebPlatformDomain
{
    public long Id { get; set; }

    public string Name { get; set; }

    public string DisplayName { get; set; }

    public string Key { get; set; }

    public bool IsMainPlatform { get; set; }

    public long? FilterSupplierId { get; set; }

    public bool ExcludeSupplierInMainPlatform { get; set; }

    public string BodySkinClass { get; set; }

    public bool CanSeeShop { get; set; }

    public bool CanSeeDocuments { get; set; }

    public bool CanSeeSwaps { get; set; }

    public bool CanSeeReturns { get; set; }

    public bool CanManco { get; set; }

    public bool CanConsignment { get; set; }

    public virtual ICollection<WebPlatformClient> WebPlatformClients { get; set; } = new List<WebPlatformClient>();
}