// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class WebUser
{
    public long Id { get; set; }

    public string Login { get; set; }

    public string Password { get; set; }

    public virtual ICollection<Contact> Contacts { get; set; } = new List<Contact>();
}