// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class WpsPrePayment
{
    public long Id { get; set; }

    public string WpsId { get; set; }

    public string CreationUrl { get; set; }

    public string ConfirmationMessage { get; set; }

    public DateTime? DatePayed { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public virtual ICollection<Document> Documents { get; set; } = new List<Document>();

    public virtual User UserCreated { get; set; }
}