// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.DataModels;

public partial class WpsToken
{
    public long Id { get; set; }

    public long SupplierId { get; set; }

    public long CountryId { get; set; }

    public string Token { get; set; }

    public bool IsDefault { get; set; }
}