// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.Models;

public partial class Employee
{
    public long Id { get; set; }

    public string FirstName { get; set; }

    public int Order { get; set; }

    public long? UserId { get; set; }

    public string TelNumber { get; set; }

    public bool HideForAgenda { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long? RecurringAppointmentId { get; set; }

    public int Pin { get; set; }

    public long? AgentId { get; set; }

    public string MobileNumber { get; set; }

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual User User { get; set; }

    public virtual User UserCreated { get; set; }
}