// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.Models;

public partial class ShopCompetitorProductLine
{
    public long Id { get; set; }

    public long ProductLineId { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public long? ShopId { get; set; }

    public virtual ProductLine ProductLine { get; set; }

    public virtual Shop Shop { get; set; }

    public virtual User UserCreated { get; set; }
}