// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FCentricProspections.Server.Models;

public partial class Shop
{
    public long Id { get; set; }

    public DateTime? OpeningDate { get; set; }

    public int? Area { get; set; }

    public int? SalesPeople { get; set; }

    public int? DisplayWindows { get; set; }

    public int? Floors { get; set; }

    public long? ShopTypeId { get; set; }

    public long? SpancoId { get; set; }

    public long? ContactId { get; set; }

    public string Name { get; set; }

    public long UserCreatedId { get; set; }

    public DateTime DateCreated { get; set; }

    public byte[] Timestamp { get; set; }

    public string SearchName { get; set; }

    public bool IsParallelSales { get; set; }

    public virtual Contact Contact { get; set; }

    public virtual ICollection<CustomerShop> CustomerShops { get; set; } = new List<CustomerShop>();

    // NEW !
    public virtual ICollection<Prospection> Prospections { get; set; } = new List<Prospection>();

    public virtual ICollection<ShopCommercialLocation> ShopCommercialLocations { get; set; } = new List<ShopCommercialLocation>();

    public virtual ICollection<ShopCompetitorBrand> ShopCompetitorBrands { get; set; } = new List<ShopCompetitorBrand>();

    public virtual ICollection<ShopCompetitorProductLine> ShopCompetitorProductLines { get; set; } = new List<ShopCompetitorProductLine>();

    public virtual ICollection<ShopContact> ShopContacts { get; set; } = new List<ShopContact>();

    public virtual ICollection<ShopDelivery> ShopDeliveries { get; set; } = new List<ShopDelivery>();

    public virtual ICollection<ShopGender> ShopGenders { get; set; } = new List<ShopGender>();

    public virtual ICollection<ShopLine> ShopLines { get; set; } = new List<ShopLine>();

    public virtual ShopType ShopType { get; set; }

    public virtual Spanco Spanco { get; set; }

    public virtual User UserCreated { get; set; }
}