// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FCentricProspections.Server.Models;

public partial class User
{
    public long Id { get; set; }

    public string Login { get; set; }

    public bool Blocked { get; set; }

    public virtual ICollection<Address> Addresses { get; set; } = new List<Address>();

    public virtual ICollection<AgeCategory> AgeCategories { get; set; } = new List<AgeCategory>();

    public virtual ICollection<BlockedType> BlockedTypes { get; set; } = new List<BlockedType>();

    public virtual ICollection<Brand> Brands { get; set; } = new List<Brand>();

    public virtual ICollection<City> Cities { get; set; } = new List<City>();

    public virtual ICollection<CommercialLocation> CommercialLocations { get; set; } = new List<CommercialLocation>();

    public virtual ICollection<CompetitorBrand> CompetitorBrands { get; set; } = new List<CompetitorBrand>();

    public virtual ICollection<ContactType> ContactTypes { get; set; } = new List<ContactType>();

    public virtual ICollection<Contact> Contacts { get; set; } = new List<Contact>();

    public virtual ICollection<Country> Countries { get; set; } = new List<Country>();

    public virtual ICollection<Currency> Currencies { get; set; } = new List<Currency>();

    public virtual ICollection<CustomerCode> CustomerCodes { get; set; } = new List<CustomerCode>();

    public virtual ICollection<CustomerLegalHistory> CustomerLegalHistories { get; set; } = new List<CustomerLegalHistory>();

    public virtual ICollection<CustomerShop> CustomerShops { get; set; } = new List<CustomerShop>();

    public virtual ICollection<CustomerType> CustomerTypes { get; set; } = new List<CustomerType>();

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual ICollection<Employee> EmployeeUserCreateds { get; set; } = new List<Employee>();

    [NotMapped]
    public virtual ICollection<Employee> EmployeeUsers { get; set; } = new List<Employee>();

    public virtual ICollection<Gender> Genders { get; set; } = new List<Gender>();

    public virtual ICollection<Language> Languages { get; set; } = new List<Language>();

    public virtual ICollection<LegalForm> LegalForms { get; set; } = new List<LegalForm>();

    public virtual ICollection<Line> Lines { get; set; } = new List<Line>();

    public virtual ICollection<PaymentCondition> PaymentConditions { get; set; } = new List<PaymentCondition>();

    public virtual ICollection<ProductLineDelivery> ProductLineDeliveries { get; set; } = new List<ProductLineDelivery>();

    public virtual ICollection<ProductLine> ProductLines { get; set; } = new List<ProductLine>();

    public virtual ICollection<Province> Provinces { get; set; } = new List<Province>();

    public virtual ICollection<Region> Regions { get; set; } = new List<Region>();

    public virtual ICollection<SalesPeriodType> SalesPeriodTypes { get; set; } = new List<SalesPeriodType>();

    public virtual ICollection<SalesPeriod> SalesPeriods { get; set; } = new List<SalesPeriod>();

    public virtual ICollection<SegmentType> SegmentTypes { get; set; } = new List<SegmentType>();

    public virtual ICollection<ShopCommercialLocation> ShopCommercialLocations { get; set; } = new List<ShopCommercialLocation>();

    public virtual ICollection<ShopCompetitorBrand> ShopCompetitorBrands { get; set; } = new List<ShopCompetitorBrand>();

    public virtual ICollection<ShopCompetitorProductLine> ShopCompetitorProductLines { get; set; } = new List<ShopCompetitorProductLine>();

    public virtual ICollection<ShopContact> ShopContacts { get; set; } = new List<ShopContact>();

    public virtual ICollection<ShopDelivery> ShopDeliveries { get; set; } = new List<ShopDelivery>();

    public virtual ICollection<ShopDeliveryOrigin> ShopDeliveryOrigins { get; set; } = new List<ShopDeliveryOrigin>();

    public virtual ICollection<ShopDeliveryState> ShopDeliveryStates { get; set; } = new List<ShopDeliveryState>();

    public virtual ICollection<ShopDeliveryType> ShopDeliveryTypes { get; set; } = new List<ShopDeliveryType>();

    public virtual ICollection<ShopGender> ShopGenders { get; set; } = new List<ShopGender>();

    public virtual ICollection<ShopLine> ShopLines { get; set; } = new List<ShopLine>();

    public virtual ICollection<ShopType> ShopTypes { get; set; } = new List<ShopType>();

    public virtual ICollection<Shop> Shops { get; set; } = new List<Shop>();

    public virtual ICollection<Spanco> Spancos { get; set; } = new List<Spanco>();

    public virtual ICollection<VatType> VatTypes { get; set; } = new List<VatType>();
}